INSERT OVERWRITE TABLE fc_inbound_request_item_l0_hive_fact
select 
warehouse_company,
inbound_request_item_id,
inbound_request_item_quantity,
inbound_request_item_updated_at,
inbound_request_item_updated_date_key,
inbound_request_item_updated_time_key,
inbound_request_item_created_at,
inbound_request_item_created_date_key,
inbound_request_item_created_time_key,
inbound_request_item_status,
inbound_request_item_created_by,
inbound_request_item_grn_id,
inbound_request_item_product_id,
inbound_request_item_updated_by,
inbound_request_consignment_type,
inbound_request_created_at,
inbound_request_created_date_key,
inbound_request_created_time_key,
inbound_request_created_by,
inbound_request_damaged_quantity,
inbound_requests_destination_location,
inbound_request_document_id,
inbound_request_document_type,
inbound_request_executive_notes,
inbound_request_external_id,
inbound_request_good_quantity,
inbound_request_entity_id,
inbound_requests_inbound_request_type,
inbound_requests_origin_party_id,
inbound_requests_origin_party_type,
inbound_request_pod_printed_at,
inbound_request_qc_verification_reason,
inbound_requests_quantity,
inbound_request_receive_type,
inbound_request_receiving_data_updated_at,
inbound_request_rejected_quantity,
inbound_requests_status,
inbound_request_unloaded_at,
inbound_request_unloaded_by,
inbound_requests_updated_at,
inbound_request_updated_date_key,
inbound_request_updated_time_key,
inbound_request_updated_by,
inbound_requests_warehouse_id,
product_id_key,
warehouse_dim_key,
inbound_request_arrived_at_gate_timestamp,
inbound_request_arrived_at_gate_date_key,
inbound_request_arrived_at_gate_time_key,
inbound_request_completed_timestamp,
inbound_request_created_timestamp,
inbound_request_ready_to_process_timestamp,
inbound_request_rejected_timestamp,
inbound_expectation_entity_type,
inbound_expectation_quantity
from (
select 'fki' as warehouse_company,
--inbound request item
iri.entityid as inbound_request_item_id,
iri.data.quantity as inbound_request_item_quantity,
iri.data.updated_at as inbound_request_item_updated_at,
lookup_date(iri.data.updated_at) as inbound_request_item_updated_date_key,
lookup_time(iri.data.updated_at) as inbound_request_item_updated_time_key,
iri.data.created_at as inbound_request_item_created_at,
lookup_date(iri.data.created_at) as inbound_request_item_created_date_key,
lookup_time(iri.data.created_at) as inbound_request_item_created_time_key,
iri.data.status as inbound_request_item_status,
iri.data.created_by as inbound_request_item_created_by,
iri.data.grn_id as inbound_request_item_grn_id,
iri.data.product_id as inbound_request_item_product_id,
iri.data.updated_by as inbound_request_item_updated_by,
--inbound request
ir.data.consignment_type as inbound_request_consignment_type,
ir.data.created_at as inbound_request_created_at,
lookup_date(ir.data.created_at) as inbound_request_created_date_key,
lookup_time(ir.data.created_at) as inbound_request_created_time_key,
ir.data.created_by as inbound_request_created_by,
ir.data.damaged_quantity as inbound_request_damaged_quantity,
ir.data.destination_location as inbound_requests_destination_location,
ir.data.document_id as inbound_request_document_id,
ir.data.document_type as inbound_request_document_type,
ir.data.executive_notes as inbound_request_executive_notes,
ir.data.external_id as inbound_request_external_id,
ir.data.good_quantity as inbound_request_good_quantity,
ir.entityid as inbound_request_entity_id,
ir.data.inbound_request_type as inbound_requests_inbound_request_type,
ir.data.origin_party_id as inbound_requests_origin_party_id,
ir.data.origin_party_type as inbound_requests_origin_party_type,
ir.data.pod_printed_at as inbound_request_pod_printed_at,
ir.data.qc_verification_reason as inbound_request_qc_verification_reason,
ir.data.quantity as inbound_requests_quantity,
ir.data.receive_type as inbound_request_receive_type,
ir.data.receiving_data_updated_at as inbound_request_receiving_data_updated_at,
ir.data.rejected_quantity as inbound_request_rejected_quantity,
ir.data.status as inbound_requests_status,
ir.data.unloaded_at as inbound_request_unloaded_at,
ir.data.unloaded_by as inbound_request_unloaded_by,
ir.data.updated_at as inbound_requests_updated_at,
lookup_date(ir.data.updated_at) as inbound_request_updated_date_key,
lookup_time(ir.data.updated_at) as inbound_request_updated_time_key,
ir.data.updated_by as inbound_request_updated_by,
ir.data.warehouse_id as inbound_requests_warehouse_id,
lookupkey('product_detail_product_id',concat(iri.data.product_id,'fki')) as product_id_key,
lookupkey('warehouse_id',ir.data.warehouse_id) as warehouse_dim_key,
if(ire.data.status = 'arrived_at_gate',ire.day,null) as inbound_request_arrived_at_gate_timestamp,
lookup_date(if(ire.data.status = 'arrived_at_gate',ire.day,null)) as inbound_request_arrived_at_gate_date_key,
lookup_time(if(ire.data.status = 'arrived_at_gate',ire.day,null)) as inbound_request_arrived_at_gate_time_key,
if(ire.data.status = 'completed',ire.day,null) as inbound_request_completed_timestamp,
if(ire.data.status = 'created',ire.day,null) as inbound_request_created_timestamp,
if(ire.data.status = 'ready_to_process',ire.day,null) as inbound_request_ready_to_process_timestamp,
if(ire.data.status = 'rejected',ire.day,null) as inbound_request_rejected_timestamp,
ir_ex.data.entity_type as inbound_expectation_entity_type,
ir_ex.data.quantity as inbound_expectation_quantity
from bigfoot_snapshot.dart_fki_scp_warehouse_inbound_request_item_1_view  as iri
left join bigfoot_snapshot.dart_fki_scp_warehouse_inbound_request_1_view as ir
on iri.data.inbound_request_id=ir.data.id
left join bigfoot_journal.dart_fki_scp_warehouse_inbound_request_event_1_view as ire
on ir.eventid=ire.eventid
left join bigfoot_snapshot.dart_fki_scp_warehouse_inbound_request_expectation_1_view ir_ex
on ir_ex.data.inbound_request_id = iri.data.inbound_request_id and ir_ex.data.product_id = iri.data.product_id
UNION ALL
select 'wsr' as warehouse_company,
--inbound request item
iri2.entityid as inbound_request_item_id,
iri2.data.quantity as inbound_request_item_quantity,
iri2.data.updated_at as inbound_request_item_updated_at,
lookup_date(iri2.data.updated_at) as inbound_request_item_updated_date_key,
lookup_time(iri2.data.updated_at) as inbound_request_item_updated_time_key,
iri2.data.created_at as inbound_request_item_created_at,
lookup_date(iri2.data.created_at) as inbound_request_item_created_date_key,
lookup_time(iri2.data.created_at) as inbound_request_item_created_time_key,
iri2.data.status as inbound_request_item_status,
iri2.data.created_by as inbound_request_item_created_by,
iri2.data.grn_id as inbound_request_item_grn_id,
iri2.data.product_id as inbound_request_item_product_id,
iri2.data.updated_by as inbound_request_item_updated_by,
--inbound request
ir2.data.consignment_type as inbound_request_consignment_type,
ir2.data.created_at as inbound_request_created_at,
lookup_date(ir2.data.created_at) as inbound_request_created_date_key,
lookup_time(ir2.data.created_at) as inbound_request_created_time_key,
ir2.data.created_by as inbound_request_created_by,
ir2.data.damaged_quantity as inbound_request_damaged_quantity,
ir2.data.destination_location as inbound_requests_destination_location,
ir2.data.document_id as inbound_request_document_id,
ir2.data.document_type as inbound_request_document_type,
ir2.data.executive_notes as inbound_request_executive_notes,
ir2.data.external_id as inbound_request_external_id,
ir2.data.good_quantity as inbound_request_good_quantity,
ir2.entityid as inbound_request_entity_id,
ir2.data.inbound_request_type as inbound_requests_inbound_request_type,
ir2.data.origin_party_id as inbound_requests_origin_party_id,
ir2.data.origin_party_type as inbound_requests_origin_party_type,
ir2.data.pod_printed_at as inbound_request_pod_printed_at,
ir2.data.qc_verification_reason as inbound_request_qc_verification_reason,
ir2.data.quantity as inbound_requests_quantity,
ir2.data.receive_type as inbound_request_receive_type,
ir2.data.receiving_data_updated_at as inbound_request_receiving_data_updated_at,
ir2.data.rejected_quantity as inbound_request_rejected_quantity,
ir2.data.status as inbound_requests_status,
ir2.data.unloaded_at as inbound_request_unloaded_at,
ir2.data.unloaded_by as inbound_request_unloaded_by,
ir2.data.updated_at as inbound_requests_updated_at,
lookup_date(ir2.data.updated_at) as inbound_request_updated_date_key,
lookup_time(ir2.data.updated_at) as inbound_request_updated_time_key,
ir2.data.updated_by as inbound_request_updated_by,
ir2.data.warehouse_id as inbound_requests_warehouse_id,
lookupkey('product_detail_product_id',concat(iri2.data.product_id,'fki')) as product_id_key,
lookupkey('warehouse_id',ir2.data.warehouse_id) as warehouse_dim_key,
if(ire2.data.status = 'arrived_at_gate',ire2.day,null) as inbound_request_arrived_at_gate_timestamp,
lookup_date(if(ire2.data.status = 'arrived_at_gate',ire2.day,null)) as inbound_request_arrived_at_gate_date_key,
lookup_time(if(ire2.data.status = 'arrived_at_gate',ire2.day,null)) as inbound_request_arrived_at_gate_time_key,
if(ire2.data.status = 'completed',ire2.day,null) as inbound_request_completed_timestamp,
if(ire2.data.status = 'created',ire2.day,null) as inbound_request_created_timestamp,
if(ire2.data.status = 'ready_to_process',ire2.day,null) as inbound_request_ready_to_process_timestamp,
if(ire2.data.status = 'rejected',ire2.day,null) as inbound_request_rejected_timestamp,
ir_ex2.data.entity_type as inbound_expected_entity_type,
ir_ex2.data.quantity as inbound_expected_quantity
from bigfoot_snapshot.dart_wsr_scp_warehouse_inbound_request_item_1_view  as iri2
left join bigfoot_snapshot.dart_wsr_scp_warehouse_inbound_request_1_view as ir2
on iri2.data.inbound_request_id=ir2.data.id
left join bigfoot_journal.dart_wsr_scp_warehouse_inbound_request_event_1_view as ire2
on ir2.eventid=ire2.eventid
left join bigfoot_snapshot.dart_wsr_scp_warehouse_inbound_request_expectation_1_view ir_ex2
on ir_ex2.data.inbound_request_id = iri2.data.inbound_request_id and ir_ex2.data.product_id = iri2.data.product_id) final_table;
