INSERT OVERWRITE TABLE fc_inbound_receiving_l0_hive_fact
select
final_table.warehouse_company as warehouse_company,
final_table.grn_id as grn_id,
final_table.grn_created_at as grn_created_at,
final_table.grn_created_by as grn_created_by,
final_table.grn_created_date_key as grn_created_date_key,
final_table.grn_created_time_key as grn_created_time_key,
final_table.grn_document_id as grn_document_id,
final_table.grn_document_type as grn_document_type,
final_table.grn_product_id as grn_product_id,
final_table.product_key as product_key,
final_table.grn_quantity as grn_quantity,
final_table.grn_updated_at as grn_updated_at,
final_table.grn_updated_date_key as grn_updated_date_key,
final_table.grn_updated_time_key as grn_updated_time_key,
final_table.grn_warehouse_id as grn_warehouse_id,
final_table.warehouse_id_key as warehouse_id_key,
final_table.irn_internal_id as irn_internal_id,
final_table.shipment_id as shipment_id,
final_table.srn_id as srn_id,
final_table.inbound_request_id as inbound_request_id,
final_table.extra as extra,
final_table.qc_pass_quantity as qc_pass_quantity,
final_table.grn_updated_by as grn_updated_by,
final_table.wid as wid
from 
(select 'fki' as warehouse_company,
grn1.entityid as grn_id,
grn1.data.created_at as grn_created_at,
grn1.data.created_by as grn_created_by,
lookup_date(grn1.data.created_at) as grn_created_date_key,
lookup_time(grn1.data.created_at) as grn_created_time_key,
grn1.data.document_id as grn_document_id,
grn1.data.document_type as grn_document_type,
grn1.data.product_id as grn_product_id,
lookupkey('product_detail_product_id', concat(grn1.data.product_id,'fki')) as product_key,
grn1.data.quantity as grn_quantity,
grn1.data.updated_at as grn_updated_at,
lookup_date(grn1.data.updated_at) as grn_updated_date_key,
lookup_time(grn1.data.updated_at) as grn_updated_time_key,
grn1.data.warehouse_id as grn_warehouse_id,
lookupkey('warehouse_id',grn1.data.warehouse_id) as warehouse_id_key,
if(grn1.data.document_type='irn',grn1.data.document_id,null) as irn_internal_id,
if(grn1.data.document_type='shipment',grn1.data.document_id,null) as shipment_id,
if(grn1.data.document_type='srn',grn1.data.document_id,null) as srn_id,
if(grn1.data.document_type in('fbf_asn','consignment'),grn1.data.document_id,null) as inbound_request_id,
1 as extra,
grn1.data.qc_pass_quantity as qc_pass_quantity,
grn1.data.updated_by as grn_updated_by,
grn1.data.wid as wid
from bigfoot_snapshot.dart_fki_scp_warehouse_goods_receipt_note_2_view as grn1
UNION ALL
select 'wsr' as warehouse_company,
grn2.entityid as grn_id,
grn2.data.created_at as grn_created_at,
grn2.data.created_by as grn_created_by,
lookup_date(grn2.data.created_at) as grn_created_date_key,
lookup_time(grn2.data.created_at) as grn_created_time_key,
grn2.data.document_id as grn_document_id,
grn2.data.document_type as grn_document_type,
grn2.data.product_id as grn_product_id,
lookupkey('product_detail_product_id', concat(grn2.data.product_id,'wsr')) as product_key,
grn2.data.quantity as grn_quantity,
grn2.data.updated_at as grn_updated_at,
lookup_date(grn2.data.updated_at) as grn_updated_date_key,
lookup_time(grn2.data.updated_at) as grn_updated_time_key,
grn2.data.warehouse_id as grn_warehouse_id,
lookupkey('warehouse_id',grn2.data.warehouse_id) as warehouse_id_key,
if(grn2.data.document_type='irn',grn2.data.document_id,null) as irn_internal_id,
if(grn2.data.document_type='shipment',grn2.data.document_id,null) as shipment_id,
if(grn2.data.document_type='srn',grn2.data.document_id,null) as srn_id,
if(grn2.data.document_type in('fbf_asn','consignment'),grn2.data.document_id,null) as inbound_request_id,
1 as extra,
grn2.data.qc_pass_quantity as qc_pass_quantity,
grn2.data.updated_by as grn_updated_by,
grn2.data.wid as wid
from bigfoot_snapshot.dart_wsr_scp_warehouse_goods_receipt_note_3_view as grn2) final_table;
