INSERT overwrite TABLE la_shipment_runsheet_fact
SELECT C_runsheet.tasklist_tracking_id AS tasklist_tracking_id,
       C_runsheet.ekl_facility_id AS ekl_facility_id,
       C_runsheet.agent_id AS last_tasklist_agent_id,
       C_runsheet.updated_at AS last_tasklist_updated_at,
       C_runsheet.document_type AS tasklist_type,
       C_runsheet.tasklist_id AS last_tasklist_id,
       C_runsheet.status AS tasklist_status,
       C_runsheet.runsheet_id AS runsheet_id,
       lookupkey('agent_id',C_runsheet.agent_id) AS last_tasklist_agent_id_key,
       lookupkey('facility_id',C_runsheet.ekl_facility_id) AS ekl_facility_id_key,
       C_runsheet.created_at AS runsheet_created_at,
       lookup_date(to_date(C_runsheet.created_at)) AS runsheet_created_at_date_key,
       'dummy1' AS dummy1,
       'dummy2' AS dummy2
FROM
  (SELECT B_runsheet.task_id AS tasklist_tracking_id,
          B_runsheet.ekl_facility_id AS ekl_facility_id,
          B_runsheet.agent_id AS agent_id,
          B_runsheet.created_at AS created_at,
          B_runsheet.updated_at AS updated_at,
          B_runsheet.document_type AS document_type,
          B_runsheet.tasklist_id AS tasklist_id,
          B_runsheet.status AS status,
          B_runsheet.runsheet_ids AS runsheet_id_n,
          FIRST_VALUE(B_runsheet.runsheet_ids) OVER (PARTITION BY B_runsheet.tasklist_id
                                                     ORDER BY B_runsheet.updated_at DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS runsheet_id,
          row_number() Over (PARTITION BY B_runsheet.tasklist_id
                             ORDER BY B_runsheet.updated_at DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS row_n
   FROM
     (SELECT A_Runsheet.agent_id AS agent_id,
             A_Runsheet.created_at AS created_at,
             A_Runsheet.ekl_facility_id AS ekl_facility_id,
             A_Runsheet.updated_at AS updated_at,
             A_Runsheet.document_type AS document_type,
             A_Runsheet.task_id AS task_id,
             A_Runsheet.status AS status,
             regexp_extract(A_Runsheet.task_id, '^[0-9]*(-)(.*)', 2) AS tasklist_id,
             regexp_extract(entityid,'^([a-zA-Z]*)(-)(.*)', 3) AS runsheet_ids
      FROM
        (SELECT entityid ,
                `data`.agent_id AS agent_id,
                `data`.created_at AS created_at,
                `data`.document_type AS document_type,
                `data`.status AS status,
                `data`.ekl_facility_id AS ekl_facility_id,
                `data`.updated_at AS updated_at,
                task_id
         FROM bigfoot_snapshot.dart_wsr_scp_ekl_lastmiletasklist_1_view LATERAL VIEW EXPLODE(`data`.task_ids)task_id AS task_id
         WHERE `data`.document_type IN ('runsheet',
                                        'pickupsheet')
           AND `data`.ekl_facility_id IN (  23,
											62,
											141,
											466,
											470,
											471,
											497,
											498,
											499,
											500,
											501,
											589,
											590,
											591,
											592,
											593,
											594,
											595,
											622,
											653,
											709,
											1199,
											1684,
											3224,
											3225,
											3277,
											3336,
											3357,
											3381,
											3411,
											3412,
											3431,
											3439,
											3440,
											3444,
											3445,
											3448,
											3453,
											3454,
											3455,
											3461,
											3464,
											3468,
											3473,
											3474,
											3478,
											3481,
											3532,
											3572,
											3579,
											3580,
											3581,
											3582,
											3589,
											3590,
											3591,
											3597,
											3613,
											3625,
											4069,
											4075
											))A_Runsheet)B_runsheet)C_runsheet
WHERE C_runsheet.row_n=1;
