INSERT overwrite TABLE la_shipment_l0_fact
SELECT 	shipment_id,
		vendor_tracking_id,
		shipment_current_status,
		shipment_current_status_date_key,
		shipment_current_status_time_key,
		destination_geo_id_key,
		ekl_shipment_type,
		customer_promise_date_key,
		customer_promise_time_key,
		logistics_promise_date_key,
		logistics_promise_time_key,
		shipment_created_at_date_key,
		shipment_created_at_time_key,
		shipment_created_at_datetime,
		vendor_id_key,
		vendor_name,
		shipment_carrier,
		fsd_assigned_hub_id_key,
		fsd_last_current_hub_id_key,
		fsd_last_current_hub_type,
		billable_weight,
		rvp_origin_geo_id_key,
		seller_id_key,
		pos_id_key,
		shipment_agent_id_key,
		transaction_id,
		amount_collected,
		seller_type,
		shipment_dg_flag,
		shipment_fragile_flag,
		lzn_classification,
		merchant_id,
		merchant_reference_id,
		shipment_first_consignment_id,
		shipment_last_consignment_id,
		shipment_first_consignment_create_datetime,
		shipment_first_consignment_create_date_key,
		shipment_first_consignment_create_time_key,
		shipment_last_consignment_create_date_key,
		shipment_last_consignment_create_datetime,
		shipment_last_consignment_eta_in_sec,
		shipment_last_consignment_eta_datetime,
		shipment_last_consignment_conn_id,
		shipment_inscan_time,
		shipment_rto_create_time,
		fsd_last_received_time,
		fsd_number_of_ofd_attempts,
		fsd_assignedhub_expected_time,
		fsd_assignedhub_received_time,
		fsd_returnedtoekl_time,
		fsd_receivedbyekl_time,
		runsheet_close_datetime,
		runsheet_close_date_key,
		ekl_delivery_datetime,
		ekl_delivery_date_key,
		ekl_delivery_time_key,
		shipment_first_ofd_datetime,
		shipment_last_ofd_datetime,
		vendor_dispatch_datetime,
		fsd_assigned_hub_sent_datetime,
		openbox_reject_datetime,
		fsd_first_dh_received_datetime,
		rvp_pickup_complete_datetime,
		shipment_rvp_pk_number_of_attempts,
		end_state_datetime,
		fsd_last_dhhub_sent_datetime,
		shipment_value,
		cod_amount_to_collect,
		payment_mode,   
		fsd_firstundeliverystatus,
		rvp_hub_id,
		rvp_hub_id_key,
		shipment_origin_facility_id_key,
		rvp_destination_facility_key,
		tasklist_tracking_id,
		ekl_facility_id,
		last_tasklist_agent_id,
		last_tasklist_updated_at,
		tasklist_type,
		last_tasklist_id,
		tasklist_status,
		runsheet_id,
		last_tasklist_agent_id_key,
		ekl_facility_id_key,
		is_cpu_vendor,
		pincode_location_type,
		seller_id,
		pos_id,
		agent_id,
		lzn_tat_target,
		rvp_complete_date_key,
		is_synergy_hub,
		vas_type,
		rvp_complete_datetime,
		reverse_shipment_type
		FROM
			(SELECT shipment_id,
			vendor_tracking_id,
			shipment_current_status,
			shipment_current_status_date_key,
			shipment_current_status_time_key,
			destination_geo_id_key,
			ekl_shipment_type,
			customer_promise_date_key,
			customer_promise_time_key,
			logistics_promise_date_key,
			logistics_promise_time_key,
			shipment_created_at_date_key,
			shipment_created_at_time_key,
			shipment_created_at_datetime,
			vendor_id_key,
			vendor_name,
			shipment_carrier,
			fsd_assigned_hub_id_key,
			fsd_last_current_hub_id_key,
			fsd_last_current_hub_type,
			billable_weight,
			rvp_origin_geo_id_key,
			seller_id_key,
			pos_id_key,
			shipment_agent_id_key,
			transaction_id,
			amount_collected,
			seller_type,
			shipment_dg_flag,
			shipment_fragile_flag,
			lzn_classification,
			merchant_id,
			merchant_reference_id,
			shipment_first_consignment_id,
			shipment_last_consignment_id,
			shipment_first_consignment_create_datetime,
			shipment_first_consignment_create_date_key,
			shipment_first_consignment_create_time_key,
			shipment_last_consignment_create_date_key,
			shipment_last_consignment_create_datetime,
			shipment_last_consignment_eta_in_sec,
			shipment_last_consignment_eta_datetime,
			shipment_last_consignment_conn_id,
			shipment_inscan_time,
			shipment_rto_create_time,
			fsd_last_received_time,
			fsd_number_of_ofd_attempts,
			fsd_assignedhub_expected_time,
			fsd_assignedhub_received_time,
			fsd_returnedtoekl_time,
			fsd_receivedbyekl_time,
			runsheet_close_datetime,
			runsheet_close_date_key,
			ekl_delivery_datetime,
			ekl_delivery_date_key,
			ekl_delivery_time_key,
			shipment_first_ofd_datetime,
			shipment_last_ofd_datetime,
			vendor_dispatch_datetime,
			fsd_assigned_hub_sent_datetime,
			openbox_reject_datetime,
			fsd_first_dh_received_datetime,
			rvp_pickup_complete_datetime,
			shipment_rvp_pk_number_of_attempts,
			end_state_datetime,
			fsd_last_dhhub_sent_datetime,
			shipment_value,
			cod_amount_to_collect,
			payment_mode,   
			fsd_firstundeliverystatus,
			rvp_hub_id,
			rvp_hub_id_key,
			shipment_origin_facility_id_key,
			rvp_destination_facility_key,
			tasklist_tracking_id,
			ekl_facility_id,
			last_tasklist_agent_id,
			last_tasklist_updated_at,
			tasklist_type,
			last_tasklist_id,
			tasklist_status,
			runsheet_id,
			last_tasklist_agent_id_key,
			ekl_facility_id_key,
			is_cpu_vendor,
			pincode_location_type,
			seller_id,
			pos_id,
			agent_id,
			lzn_tat_target,
			rvp_complete_date_key,
			is_synergy_hub,
			vas_type,
			rvp_complete_datetime,
			reverse_shipment_type
			FROM
						(SELECT DISTINCT sv.entityid AS shipment_id,
						sv.vendor_tracking_id AS vendor_tracking_id, 
						sv.shipment_current_status AS shipment_current_status,
						lookup_date(cast(sv.updatedat/1000 AS TIMESTAMP)) AS shipment_current_status_date_key,
						lookup_time(cast(sv.updatedat/1000 AS TIMESTAMP)) AS shipment_current_status_time_key,
						lookupkey('pincode', sv.destination_address_pincode) AS destination_geo_id_key,
						sv.shipment_type AS ekl_shipment_type,
						lookup_date(sv.customer_sla) AS customer_promise_date_key,
						lookup_time(sv.customer_sla) AS customer_promise_time_key,
						lookup_date(sv.design_sla) AS logistics_promise_date_key,
						lookup_time(sv.design_sla) AS logistics_promise_time_key,
						lookup_date(sv.created_at) AS shipment_created_at_date_key,
						lookup_time(sv.created_at) AS shipment_created_at_time_key,
						sv.created_at AS shipment_created_at_datetime,
						lookupkey('vendor_id', sv.vendor_id) AS vendor_id_key,
						(CASE 	WHEN sv.vendor_id = 200 THEN 'flipkartlogistics' 
								WHEN sv.vendor_id = 207 THEN 'flipkartlogistics-cod' 
								WHEN sv.vendor_id = 242 THEN 'flipkartreverse'  
								ELSE NULL END) AS vendor_name,
						IF 		(sv.vendor_id = '',
								'VNF',
								'FSD') AS shipment_carrier,
						lookupkey('facility_id',sr.fsd_assigned_hub_id) AS fsd_assigned_hub_id_key,
						lookupkey('facility_id',sv.fsd_last_current_hub_id) AS fsd_last_current_hub_id_key,
						sv.fsd_last_current_hub_type AS fsd_last_current_hub_type,
						sv.ekl_billable_weight AS billable_weight,
						IF 		(sv.shipment_type = 'rvp',
								lookupkey('pincode', sv.rvp_origin_geo_id),
                                NULL ) AS rvp_origin_geo_id_key,
						lookupkey('seller_id', sv.seller_id) AS seller_id_key,
						lookupkey('device_id', CAST(SPLIT(sv.pos_id, "-") [1] AS INT)) AS pos_id_key,
						lookupkey('agent_id', sv.agent_id) AS shipment_agent_id_key,
						sv.transaction_id AS transaction_id,
						sv.amount_collected AS amount_collected,
						IF 		(lower(sv.source_address_type) =	'warehouse',
																	'WSR',
																	'FA') AS seller_type,
						IF 		(concat_ws("-", sv.sv_attribute) LIKE '%dangerous%',
																	1,
																	0) AS shipment_dg_flag,
                        IF 		(concat_ws("-", sv.sv_attribute) LIKE '%ragile%',
																	1,
																	0) AS shipment_fragile_flag,
						IF (sv.lzn_classification IS NOT NULL, sv.lzn_classification, sr.lzn_classification) as lzn_classification,
						slog.merchant_id AS merchant_id,
						slog.merchant_reference_id AS merchant_reference_id,
						sc.shipment_first_consignment_id,
						sc.shipment_last_consignment_id,
						sc.shipment_first_consignment_create_datetime,
						sc.shipment_first_consignment_create_date_key,
						sc.shipment_first_consignment_create_time_key,
						sc.shipment_last_consignment_create_date_key,
						sc.shipment_last_consignment_create_datetime,
						sc.shipment_last_consignment_eta_in_sec,
						sc.shipment_last_consignment_eta_datetime,
						sc.shipment_last_consignment_conn_id,
						sr.shipment_inscan_time,
						sr.shipment_rto_create_time,
						sr.fsd_last_received_time,
						sr.fsd_number_of_ofd_attempts,
						sr.fsd_assignedhub_expected_time,
						sr.fsd_assignedhub_received_time,
						sr.fsd_returnedtoekl_time,
						sr.fsd_receivedbyekl_time,
						sr.runsheet_close_datetime,
						lookup_date(sr.runsheet_close_datetime) AS runsheet_close_date_key,
						sr.ekl_delivery_datetime,
						lookup_date(sr.ekl_delivery_datetime) AS ekl_delivery_date_key,
						lookup_time(sr.ekl_delivery_datetime) AS ekl_delivery_time_key,	
						sr.shipment_first_ofd_datetime,
						sr.shipment_last_ofd_datetime,
						sr.vendor_dispatch_datetime,
						sr.fsd_assigned_hub_sent_datetime,
						sr.openbox_reject_datetime,
						sr.fsd_first_dh_received_datetime,
						sr.rvp_pickup_complete_datetime,
						sr.shipment_rvp_pk_number_of_attempts,
						sr.end_state_datetime,
						sr.fsd_last_dhhub_sent_datetime,
						sr.shipment_value,
						sr.cod_amount_to_collect,
						sr.payment_mode,
						sr.fsd_firstundeliverystatus,
						sr.rvp_hub_id,
						lookupkey('facility_id',sr.rvp_hub_id) AS rvp_hub_id_key,
						lookupkey('facility_id',IF (sv.source_address_id IS NOT NULL
						AND sv.source_address_id <> 0,sv.source_address_id,sr.source_facility_id)) AS shipment_origin_facility_id_key,
						IF (sv.shipment_type = 'rvp',lookupkey('facility_id',IF (sv.destination_address_id IS NOT NULL
						AND sv.destination_address_id <> 0,sv.destination_address_id,sr.source_facility_id)),NULL) AS rvp_destination_facility_key,
						rd.tasklist_tracking_id AS tasklist_tracking_id,
						rd.ekl_facility_id AS ekl_facility_id,
						rd.last_tasklist_agent_id AS last_tasklist_agent_id,
						rd.last_tasklist_updated_at AS last_tasklist_updated_at,
						rd.tasklist_type AS tasklist_type,
						rd.last_tasklist_id AS last_tasklist_id,
						rd.tasklist_status AS tasklist_status,
						rd.runsheet_id AS runsheet_id,
						rd.last_tasklist_agent_id_key AS last_tasklist_agent_id_key,
						rd.ekl_facility_id_key AS ekl_facility_id_key,
						rd.is_cpu_vendor as is_cpu_vendor,
						lt.location_type AS pincode_location_type,
						sv.seller_id as seller_id,
						CAST(SPLIT(sv.pos_id, "-") [1] AS INT) as pos_id,
						sv.agent_id as agent_id,
						IF (sv.lzn_tat_target IS NOT NULL, sv.lzn_tat_target, sr.lzn_tat_target) as lzn_tat_target,
						lookup_date(sr.rvp_complete_datetime) AS rvp_complete_date_key,
						syn.is_synergy_hub as is_synergy_hub,
						sr.vas_type as vas_type,
						sr.rvp_complete_datetime AS rvp_complete_datetime,
						IF(sv.shipment_type = 'rvp',IF(sr.vas_type = 'Product Exchange','PREXO',IF(sr.vas_type = 'Replacement','Replacement','Pickup_Only')),NULL) AS reverse_shipment_type
		FROM bigfoot_external_neo.scp_ekl__la_shipment_l0_snapshot_fact sv 
		LEFT OUTER JOIN
						( 	SELECT DISTINCT refid AS shipment_id,
							`data`.merchant_id AS merchant_id,
							`data`.merchant_reference_id AS merchant_reference_id
							FROM bigfoot_snapshot.dart_wsr_scp_ekl_b2clogisticsrequest_1_view_total LATERAL VIEW explode(`data`.ekl_reference_ids) reference_id AS refid) slog 
							ON sv.entityid = slog.shipment_id
		LEFT OUTER JOIN bigfoot_external_neo.scp_ekl__la_shipment_l0_shipmentgroup_fact sc ON sv.vendor_tracking_id = sc.vendor_tracking_id
		LEFT OUTER JOIN bigfoot_external_neo.scp_ekl__la_shipment_l0_journal_fact sr ON sr.entityid = sv.entityid
		LEFT OUTER JOIN
						(	SELECT DISTINCT `data`.group_id AS last_group_id,
							`data`.cutoff AS last_conn_cutoff_in_sec
							FROM bigfoot_snapshot.dart_wsr_scp_ekl_connection_1_view_total) last_conn ON last_conn.last_group_id = sc.shipment_last_consignment_conn_id
		LEFT OUTER JOIN bigfoot_external_neo.scp_ekl__la_shipment_l0_runsheet_fact rd ON sv.vendor_tracking_id = rd.last_tasklist_id
		LEFT OUTER JOIN
						(	SELECT DISTINCT pincode,
							location_type
							FROM bigfoot_common.large_pincode_location_type) lt ON lt.pincode = sv.location_pincode
		LEFT OUTER JOIN	bigfoot_common.la_synergy_hub_classification syn on syn.facility_id = IF(sv.fsd_assigned_hub_id is not null and sv.fsd_assigned_hub_id <> 0,sv.fsd_assigned_hub_id,sr.fsd_assigned_hub_id)) FSD
		UNION ALL
		SELECT 
		shipment_id,
		vendor_tracking_id,
		shipment_current_status,
		shipment_current_status_date_key,
		shipment_current_status_time_key,
		destination_geo_id_key,
		ekl_shipment_type,
		customer_promise_date_key,
		customer_promise_time_key,
		logistics_promise_date_key,
		logistics_promise_time_key,
		shipment_created_at_date_key,
		shipment_created_at_time_key,
		shipment_created_at_datetime,
		vendor_id_key,
		vendor_name,
		shipment_carrier,
		assigned_hub_id,
		last_current_hub_id,
		last_current_hub_type,
		billable_weight,
		rvp_origin_geo_id_key,
		seller_id_key,
		pos_id_key,
		shipment_agent_id_key,
		transaction_id,
		amount_collected,
		seller_type,
		shipment_dg_flag,
		shipment_fragile_flag,
		lzn_classification,
		merchant_id,
		merchant_reference_id,
		shipment_first_consignment_id,
		shipment_last_consignment_id,
		shipment_first_consignment_create_datetime,
		shipment_first_consignment_create_date_key,
		shipment_first_consignment_create_time_key,
		shipment_last_consignment_create_date_key,
		shipment_last_consignment_create_datetime,
		shipment_last_consignment_eta_in_sec,
		shipment_last_consignment_eta_datetime,
		shipment_last_consignment_conn_id,
		shipment_inscan_time,
		shipment_rto_create_time,
		last_received_time,
		number_of_ofd_attempts,
		assignedhub_expected_time,
		assignedhub_received_time,
		returnedtoekl_time,
		receivedbyekl_time,
		runsheet_close_datetime,
		runsheet_close_date_key,
		ekl_delivery_datetime,
		ekl_delivery_date_key,
		ekl_delivery_time_key,
		shipment_first_ofd_datetime,
		shipment_last_ofd_datetime,
		vendor_dispatch_datetime,
		assigned_hub_sent_datetime,
		openbox_reject_datetime,
		first_dh_received_datetime,
		rvp_pickup_complete_datetime,
		shipment_rvp_pk_number_of_attempts,
		end_state_datetime,
		last_dhhub_sent_datetime,
		shipment_value,
		cod_amount_to_collect,
		payment_mode,
		firstundeliverystatus,
		rvp_hub_id,
		rvp_hub_id_key,
		shipment_origin_facility_id_key,
		rvp_destination_facility_key,
		tasklist_tracking_id,
		ekl_facility_id,
		last_tasklist_agent_id,
		last_tasklist_updated_at,
		tasklist_type,
		last_tasklist_id,
		tasklist_status,
		runsheet_id,
		last_tasklist_agent_id_key,
		ekl_facility_id_key,
		is_cpu_vendor,
		pincode_location_type,
		seller_id,
		pos_id,
		agent_id,
		lzn_tat_target,
		rvp_complete_date_key,
		NULL AS is_synergy_hub,
		NULL AS vas_type,
		NULL AS rvp_complete_datetime,
		NULL AS reverse_shipment_type
		FROM bigfoot_external_neo.scp_ekl__la_shipment_l0_3PL_fact) FSD_3PL;
