INSERT OVERWRITE TABLE shipment_facility_l1_90_fact
select 
A.vendor_tracking_id AS vendor_tracking_id,
A.consignment_id AS incoming_consignment_id,
A.bag_id AS incoming_bag_id,
A.consignment_system_weight AS incoming_consignment_system_weight,
A.consignment_connection_id AS incoming_consignment_connection_id,
A.consignment_type AS incoming_consignment_type,
A.consignment_mode AS incoming_consignment_mode,
A.connection_type AS incoming_connection_type,
A.connection_transit_type AS incoming_connection_transit_type,
A.connection_code AS incoming_connection_code,
A.connection_frequency_type AS incoming_connection_frequency_type,
A.consignment_status AS incoming_consignment_status,
A.consignment_co_loader AS incoming_consignment_co_loader,
A.consignment_breach_flag AS incoming_consignment_breach_flag,
A.consignment_movement_flag AS incoming_consignment_movement_flag,
A.consignment_no_of_bags AS incoming_consignment_no_of_bags,
A.consignment_no_of_shipments AS incoming_consignment_no_of_shipments,
A.consignment_tms_compliant_flag AS incoming_consignment_tms_compliant_flag,
A.consignment_creation_delay_in_hours AS incoming_consignment_creation_delay_in_hours,
A.consignment_source_hub_type AS incoming_consignment_source_hub_type,
A.consignment_destination_hub_type AS incoming_consignment_destination_hub_type,
A.consignment_source_hub_id  AS incoming_consignment_source_hub_id ,
A.consignment_destination_hub_id  AS incoming_consignment_destination_hub_id,
A.consignment_source_hub_id_key AS incoming_consignment_source_hub_id_key,
A.consignment_destination_hub_id_key AS incoming_consignment_destination_hub_id_key,
A.connection_cut_off_datetime AS incoming_connection_cut_off_datetime,
A.consignment_create_datetime AS incoming_consignment_create_datetime,
A.consignment_create_unixseconds AS incoming_consignment_create_unixseconds,
A.consignment_status_date_time AS incoming_consignment_status_date_time,
A.consignment_eta_datetime AS incoming_consignment_eta_datetime,
A.consignment_received_datetime AS incoming_consignment_received_datetime,
A.bag_tracking_id AS incoming_bag_tracking_id,
A.bag_service_type AS incoming_bag_service_type,
A.bag_seal_id AS incoming_bag_seal_id,
A.bag_current_status AS incoming_bag_current_status,
A.bag_category AS incoming_bag_category,
A.bag_no_of_shipments AS incoming_bag_no_of_shipments,
A.bag_eta_update_reason AS incoming_bag_eta_update_reason,
A.bag_system_weight AS incoming_bag_system_weight,
A.bag_source_hub_id AS incoming_bag_source_hub_id,
A.bag_current_hub_id AS incoming_bag_current_hub_id,
A.bag_destination_hub_id AS incoming_bag_destination_hub_id,
A.bag_source_hub_id_key AS incoming_bag_source_hub_id_key,
A.bag_current_hub_id_key AS incoming_bag_current_hub_id_key,
A.bag_destination_hub_id_key AS incoming_bag_destination_hub_id_key,
A.bag_created_hub_type AS incoming_bag_created_hub_type,
A.bag_current_hub_type AS incoming_bag_current_hub_type,
A.bag_destination_hub_type AS incoming_bag_destination_hub_type,
A.bag_created_at_datetime AS incoming_bag_created_at_datetime,
A.bag_open_datetime AS incoming_bag_open_datetime,
A.bag_closed_datetime AS incoming_bag_closed_datetime,
A.bag_connected_datetime AS incoming_bag_connected_datetime,
A.bag_destination_hub_inscan_datetime AS incoming_bag_destination_hub_inscan_datetime,
A.bag_receive_datetime AS incoming_bag_receive_datetime,
A.bag_last_update_datetime AS incoming_bag_last_update_datetime,
A.hop_source_type AS incoming_hop_source_type,
B.consignment_id AS outgoing_consignment_id,
B.bag_id AS outgoing_bag_id,
B.consignment_system_weight AS outgoing_consignment_system_weight,
B.consignment_connection_id AS outgoing_consignment_connection_id,
B.consignment_type AS outgoing_consignment_type,
B.consignment_mode AS outgoing_consignment_mode,
B.connection_type AS outgoing_connection_type,
B.connection_transit_type AS outgoing_connection_transit_type,
B.connection_code AS outgoing_connection_code,
B.connection_frequency_type AS outgoing_connection_frequency_type,
B.consignment_status AS outgoing_consignment_status,
B.consignment_co_loader AS outgoing_consignment_co_loader,
B.consignment_breach_flag AS outgoing_consignment_breach_flag,
B.consignment_movement_flag AS outgoing_consignment_movement_flag,
B.consignment_no_of_bags AS outgoing_consignment_no_of_bags,
B.consignment_no_of_shipments AS outgoing_consignment_no_of_shipments,
B.consignment_tms_compliant_flag AS outgoing_consignment_tms_compliant_flag,
B.consignment_creation_delay_in_hours AS outgoing_consignment_creation_delay_in_hours,
B.consignment_source_hub_type AS outgoing_consignment_source_hub_type,
B.consignment_destination_hub_type AS outgoing_consignment_destination_hub_type,
B.consignment_source_hub_id  AS outgoing_consignment_source_hub_id ,
B.consignment_destination_hub_id  AS outgoing_consignment_destination_hub_id, 
B.consignment_source_hub_id_key AS outgoing_consignment_source_hub_id_key,
B.consignment_destination_hub_id_key AS outgoing_consignment_destination_hub_id_key,
B.connection_cut_off_datetime AS outgoing_connection_cut_off_datetime,
B.consignment_create_datetime AS outgoing_consignment_create_datetime,
B.consignment_create_unixseconds AS outgoing_consignment_create_unixseconds,
B.consignment_status_date_time AS outgoing_consignment_status_date_time,
B.consignment_eta_datetime AS outgoing_consignment_eta_datetime,
B.consignment_received_datetime AS outgoing_consignment_received_datetime,
B.bag_tracking_id AS outgoing_bag_tracking_id,
B.bag_service_type AS outgoing_bag_service_type,
B.bag_seal_id AS outgoing_bag_seal_id,
B.bag_current_status AS outgoing_bag_current_status,
B.bag_category AS outgoing_bag_category,
B.bag_no_of_shipments AS outgoing_bag_no_of_shipments,
B.bag_eta_update_reason AS outgoing_bag_eta_update_reason,
B.bag_system_weight AS outgoing_bag_system_weight,
B.bag_source_hub_id AS outgoing_bag_source_hub_id,
B.bag_current_hub_id AS outgoing_bag_current_hub_id,
B.bag_destination_hub_id AS outgoing_bag_destination_hub_id,
B.bag_source_hub_id_key AS outgoing_bag_source_hub_id_key,
B.bag_current_hub_id_key AS outgoing_bag_current_hub_id_key,
B.bag_destination_hub_id_key AS outgoing_bag_destination_hub_id_key,
B.bag_created_hub_type AS outgoing_bag_created_hub_type,
B.bag_current_hub_type AS outgoing_bag_current_hub_type,
B.bag_destination_hub_type AS outgoing_bag_destination_hub_type,
B.bag_created_at_datetime AS outgoing_bag_created_at_datetime,
B.bag_open_datetime AS outgoing_bag_open_datetime,
B.bag_closed_datetime AS outgoing_bag_closed_datetime,
B.bag_connected_datetime AS outgoing_bag_connected_datetime,
B.bag_destination_hub_inscan_datetime AS outgoing_bag_destination_hub_inscan_datetime,
B.bag_receive_datetime AS outgoing_bag_receive_datetime,
B.bag_last_update_datetime AS outgoing_bag_last_update_datetime,
B.hop_source_type AS outgoing_hop_source_type
FROM 
(select
consignment_id,
bag_id,
vendor_tracking_id,
consignment_system_weight,
consignment_connection_id,
consignment_type,
consignment_mode,
connection_type,
connection_transit_type,
connection_code,
connection_frequency_type,
consignment_status,
consignment_co_loader,
consignment_breach_flag,
consignment_movement_flag,
consignment_no_of_bags,
consignment_no_of_shipments,
consignment_tms_compliant_flag,
consignment_creation_delay_in_hours,
consignment_source_hub_type,
consignment_destination_hub_type,
consignment_source_hub_id ,
consignment_destination_hub_id,
consignment_source_hub_id_key,
consignment_destination_hub_id_key,
connection_cut_off_datetime,
consignment_create_datetime,
consignment_create_unixseconds,
consignment_status_date_time,
consignment_eta_datetime,
consignment_received_datetime,
bag_tracking_id,
bag_service_type,
bag_seal_id,
bag_current_status,
bag_category,
bag_no_of_shipments,
bag_eta_update_reason,
bag_system_weight,
bag_source_hub_id,
bag_current_hub_id,
bag_destination_hub_id,
bag_source_hub_id_key,
bag_current_hub_id_key,
bag_destination_hub_id_key,
bag_created_hub_type,
bag_current_hub_type,
bag_destination_hub_type,
bag_created_at_datetime,
bag_open_datetime,
bag_closed_datetime,
bag_connected_datetime,
bag_destination_hub_inscan_datetime,
bag_receive_datetime,
bag_last_update_datetime,
hop_source_type,
ROW_NUMBER() OVER (PARTITION BY vendor_tracking_id ORDER BY consignment_create_unixseconds ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as rank
from bigfoot_external_neo.scp_ekl__shipment_facility_l0_90_fact
where consignment_create_unixseconds is not null) A
left outer join
(select
consignment_id,
bag_id,
vendor_tracking_id,
consignment_system_weight,
consignment_connection_id,
consignment_type,
consignment_mode,
connection_type,
connection_transit_type,
connection_code,
connection_frequency_type,
consignment_status,
consignment_co_loader,
consignment_breach_flag,
consignment_movement_flag,
consignment_no_of_bags,
consignment_no_of_shipments,
consignment_tms_compliant_flag,
consignment_creation_delay_in_hours,
consignment_source_hub_type,
consignment_destination_hub_type,
consignment_source_hub_id ,
consignment_destination_hub_id,
consignment_source_hub_id_key,
consignment_destination_hub_id_key,
connection_cut_off_datetime,
consignment_create_datetime,
consignment_create_unixseconds,
consignment_status_date_time,
consignment_eta_datetime,
consignment_received_datetime,
bag_tracking_id,
bag_service_type,
bag_seal_id,
bag_current_status,
bag_category,
bag_no_of_shipments,
bag_eta_update_reason,
bag_system_weight,
bag_source_hub_id,
bag_current_hub_id,
bag_destination_hub_id,
bag_source_hub_id_key,
bag_current_hub_id_key,
bag_destination_hub_id_key,
bag_created_hub_type,
bag_current_hub_type,
bag_destination_hub_type,
bag_created_at_datetime,
bag_open_datetime,
bag_closed_datetime,
bag_connected_datetime,
bag_destination_hub_inscan_datetime,
bag_receive_datetime,
bag_last_update_datetime,
hop_source_type,
ROW_NUMBER() OVER (PARTITION BY vendor_tracking_id ORDER BY consignment_create_unixseconds ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)  as rank 
from  bigfoot_external_neo.scp_ekl__shipment_facility_l0_90_fact
where consignment_create_unixseconds is not null
) B on A.vendor_tracking_id = B.vendor_tracking_id and A.rank+1 = B.rank;

