INSERT OVERWRITE TABLE goods_recon_l2_hive_fact
select 
grn.return_item_id                ,
grn.return_id                     ,
grn.order_item_id                 ,
grn.return_item_quantity          ,
grn.return_item_shipment_id       ,
grn.return_item_tracking_id       ,
grn.courier_name                  ,
grn.return_courier_bucket,
grn.return_quantity_recvd_in_wh    ,
grn.return_quantity_rvp_done       ,
grn.return_item_notional_value    ,
grn.return_reason                  ,
grn.return_quantity_qc_passed      ,
grn.return_quantity_qc_failed      ,
grn.oms_qc_reason                  ,
grn.oms_qc_comment                 ,
grn.tenant_id                      ,
grn.seller_id                      ,
grn.seller_bucket,
grn.return_sub_reason               ,
grn.exchange_fsn_key                ,
grn.exchange_fsn					,
grn.return_pickup_promise_date      ,
grn.external_order_id               ,
grn.return_status                   ,
grn.return_to_address_id            ,
grn.return_customer_will_send       ,
grn.return_action                   ,
grn.return_type                     ,
grn.return_request_channel          ,
grn.return_amount                   ,
grn.return_comments                 ,
grn.returned_product_id_key         ,
grn.return_request_date             , 
grn.return_reason_bucket_key                  ,
grn.return_courier_name_key                   ,
grn.seller_id_key                             ,
grn.return_pickup_promise_date_key            ,
grn.return_product_listing_id_key             ,
grn.return_request_date_key                   ,
grn.order_id                        ,        
grn.order_external_id               ,           
grn.order_item_selling_price        ,           
grn.order_item_seller_id            ,           
grn.order_item_seller_id_key        ,           
grn.order_item_quantity             ,                    
grn.order_shipping_address_id_key   ,           
grn.return_item_product_title             ,
grn.return_item_product_id              ,
grn.return_item_product_id_key      ,
grn.return_item_category_id         ,
grn.order_item_type,
grn.order_item_date,
si.shipment_item_id,
si.shipment_display_id,
si.shipment_id,
si.shipment_return_warehouse_id,
si.shipment_entity_type as shipment_type,
si.shipment_destination_type, 
if(si.shipment_status='received','rvp','rto') as wh_rvp_rto_flag,
si.shipment_item_status,
si.shipment_item_quantity,
si.shipment_courier_name, -- need to check
si.shipment_item_is_excess,
si.shipment_is_tampered,
si.shipment_warehouse_id as warehouse_id,
si.shipment_item_order_item_id,
grn.return_numdate,
grn.return_numdate_key,
if(grn.return_customer_will_send=TRUE,1,0) as return_customer_will_return,
grn.action_override_count,
if(grn.return_amount is null,grn.order_item_selling_price,substr(grn.return_amount,1,length(grn.return_amount)-2)) as return_item_value
from
(
select
rtn.return_id                     ,
rtn.return_item_id                ,
rtn.order_item_id                 ,
rtn.return_item_quantity          ,
rtn.return_item_shipment_id       ,
rtn.return_item_tracking_id       ,
rtn.courier_name                  ,
if(rtn.courier_name is null,'No_Courier_Found',if (rtn.courier_name in ('flipkartlogistics','flipkartlogistics-cod'),'EKL','3PL')) as return_courier_bucket,
null as return_quantity_recvd_in_wh    ,
null as return_quantity_rvp_done       ,
null as return_item_notional_value ,
return_item_reason as return_reason,
null as return_quantity_qc_passed      ,
null as return_quantity_qc_failed      ,
null as oms_qc_reason                  ,
null as oms_qc_comment                 ,
rtn.tenant_id                      ,
rtn.seller_id                      ,
if(seller_id like '%wsr%','WSR', 'NonWSR') as seller_bucket,
rtn.return_item_sub_reason as return_sub_reason               ,
rtn.exchange_fsn_key                ,
rtn.exchange_fsn					,
rtn.return_item_pickup_promise_date as return_pickup_promise_date      ,
null as external_order_id               ,
rtn.return_item_status as return_status,
rtn.return_item_to_address_id as return_to_address_id            ,
rtn.return_customer_will_send       ,
rtn.return_action                   ,
rtn.return_type                     ,
rtn.return_request_channel          ,
rtn.return_amount                   ,
rtn.return_comments                 ,
null as returned_product_id_key         ,
rtn.return_item_request_date as return_request_date             ,
rtn.return_item_reason_bucket_key as return_reason_bucket_key                  ,
rtn.return_item_courier_name_key as return_courier_name_key                   ,
rtn.seller_id_key                             ,
rtn.return_item_pickup_promise_date_key as return_pickup_promise_date_key            ,
null as return_product_listing_id_key             ,
--rtn.shipment_picked_marked_date_key           ,
rtn.return_item_request_date_key as return_request_date_key                   ,
--ord.order_item_id                   ,     
ord.order_id                        ,        
ord.order_external_id               ,           
ord.order_item_selling_price        ,           
ord.order_item_seller_id            ,           
ord.order_item_seller_id_key        ,           
ord.order_item_quantity             ,                    
ord.order_shipping_address_id_key   ,           
ord.order_item_title as return_item_product_title             ,
ord.order_item_product_id as return_item_product_id              ,
ord.order_item_product_id_key as return_item_product_id_key      ,
ord.order_item_category_id as return_item_category_id         ,
ord.order_item_type,
ord.order_item_date,
--ord.account_id,
If (coalesce(rh.approve_date,0)>coalesce(rh.service_approve_return_date,0),rh.approve_date,rh.service_approve_return_date) as return_numdate,
lookup_date(If(coalesce(rh.approve_date,0)>coalesce(rh.service_approve_return_date,0),rh.approve_date,rh.service_approve_return_date)) as return_numdate_key,
rh.action_override_count
from bigfoot_external_neo.scp_rrr__return_l1_fact rtn         
left outer join bigfoot_external_neo.scp_oms__order_item_unit_s1_fact ord on (rtn.order_item_id=ord.order_item_id)
left outer join bigfoot_external_neo.scp_rrr__return_histories_l1_fact rh on (rtn.return_item_id=rh.return_item_id)
union
select 
pickup_id as return_id,
pickup_item_id as return_item_id,
order_item_id as order_item_id,
pickup_quantity as return_item_quantity,
pickup_shipment_id as return_item_shipment_id,
pickup_tracking_id as return_item_tracking_id,
courier_name as courier_name,
if(courier_name is null,'No_Courier_Found',if (courier_name in ('flipkartlogistics','flipkartlogistics-cod'),'EKL','3PL')) as return_courier_bucket,
quantity_received_in_wh as return_quantity_recvd_in_wh,
null as return_quantity_rvp_done,
notional_value as return_item_notional_value,
null as return_reason,
qty_qc_passed as return_quantity_qc_passed,
qty_qc_failed as return_quantity_qc_failed,
null as oms_qc_reason,
null as oms_qc_comment,
null as tenant_id,
seller_id,
if(seller_id like '%wsr%','WSR', 'NonWSR') as seller_bucket,
null as return_sub_reason,
null as exchange_fsn_key,
null as exchange_fsn,
pickup_promise_date as return_pickup_promise_date,
null as external_order_id,
pickup_status as return_status,
pickup_to_address_id as return_to_address_id,
customer_will_return as return_customer_will_send,
actions as return_action,
'prexo_return' as return_type,
'NA' as return_request_channel,
null as return_amount,
'NA' as return_comments,
null as returned_product_id_key,
pickup_request_date as return_request_date,
null as return_reason_bucket_key,
null as return_courier_name_key,
seller_id_key,
pickup_promise_date_key as return_pickup_promise_date_key,
null as return_product_listing_id_key,
pickup_request_date_key as return_request_date_key,
--reference_id as order_id,
order_item_id as order_id,
null as order_external_id,
null as order_item_selling_price,
null as order_item_seller_id,
null as order_item_seller_id_key,
null as order_item_quantity,
null as order_shipping_address_id_key,
title as return_item_product_title,
product_id as return_item_product_id,
lookupkey('product_detail_product_id',product_id) as  return_item_product_id_key,
category_id as return_item_category_id,
null as order_item_type,
null as order_item_date,
--null as account_id,
pickup_request_date as return_numdate,
pickup_request_date_key as return_numdate_key,
null as action_override_count
from bigfoot_external_neo.scp_ekl__pickup_l0_fact
) grn
left outer join bigfoot_external_neo.scp_warehouse__fc_shipment_item_l0_hive_fact si on (grn.order_item_id=si.shipment_item_order_item_id and grn.return_item_tracking_id=si.shipment_display_id);
