INSERT OVERWRITE TABLE smart_pickup_l2_hive_fact
Select
sm.shipment_id as shipment_id,
sm.ekl_shipment_type,
sm.reverse_shipment_type,
max(sm.shipment_value) as shipment_value,
sm.seller_type,
--sm.ekl_fin_zone,
--sm.shipment_carrier,
--sm.shipment_rvp_pk_number_of_attempts,
--sm.source_address_pincode,
--sm.fsd_assigned_hub_id,
--sm.reverse_pickup_hub_id,
--sm.shipment_first_received_dh_id,
--sm.shipment_last_received_dh_id,
sm.agent_id as agent_id,
sm.rvp_help_line_dialed,
sm.tl_timestamp,
sm.cs_override,
sm.shipment_status_reason,
sm.outer_tl_result,
sm.outer_fe_result,
sm.reason_code,
sm.team_leader_ldap,
sm.return_type,
sm.shipment_status_code,
--sm.wsn_display_id,
--sm.pv_max_numdate,
--sm.pv_max_num_date_key,
--sm.pv_max_num_time_key,
--sm.pv_bucket,
--sm.product_id_key,
--sm.seller_id,
--sm.return_reason,
--sm.return_sub_reason,
---sm.detailed_pv_reasons,
--sm.detailed_pv_sub_reasons,
--sm.initial_pv_done_by,
--sm.qc_return_type,
--sm.inventory_item_wid,
--sm.re_pv_done_by,
--sm.order_id,
max(sm.fe_timestamp) as fe_timestamp,
max(sm.is_match*sm.fe_result*sm.ismandatory*sm.cs_override) as inaccuracy,
max(sm.is_match*sm.outer_fe_result*sm.ismandatory*sm.cs_override) as outer_inaccuracy,

max(sm.pk_wo_cs_or_afr_fail) as pk_wo_cs_or_afr_fail,
max(sm.reverse_misshipment) as reverse_misshipment,
max(sm.imei_mismatch) as imei_mismatch,
concat_ws("--",collect_list(case when sm.is_match*sm.fe_result*sm.ismandatory*sm.cs_override=1 then sm.check_name else null end)) as checks_inaccurate,
concat_ws("--",collect_list(sm.check_name)) as checks,
concat_ws("--",collect_list(CAST(sm.is_match*sm.outer_fe_result*sm.ismandatory*sm.cs_override as STRING))) as check_result,
sm.shipment_rvp_pk_number_of_attempts,
concat_ws("--",collect_list(CAST(sm.ismandatory as STRING))) as ismandatory_list,
concat_ws("--",collect_list(CAST(sm.fe_result as STRING))) as fe_result_list,
concat_ws("--",collect_list(CAST(sm.tl_result as STRING))) as tl_result_list,
max(sm.sub_item_name) as sub_item_name,
max(sm.is_match*sm.tl_result*sm.ismandatory*sm.cs_override) as tl_inaccuracy,
max(sm.is_match*sm.outer_tl_result*sm.ismandatory*sm.cs_override) as tl_outer_inaccuracy,
concat_ws("--",collect_list(case when sm.is_match*sm.tl_result*sm.ismandatory*sm.cs_override=1 then sm.check_name else null end)) as tl_checks_inaccurate,
concat_ws("--",collect_list(CAST(sm.is_match*sm.outer_tl_result*sm.ismandatory*sm.cs_override as STRING))) as tl_check_results
from bigfoot_external_neo.scp_ekl__smart_pickup_l1_hive_fact sm
group by 
sm.shipment_id,
sm.ekl_shipment_type,
sm.reverse_shipment_type,
sm.seller_type,
sm.agent_id,
sm.rvp_help_line_dialed,
sm.tl_timestamp,
sm.cs_override,
sm.shipment_status_reason,
sm.outer_tl_result,
sm.outer_fe_result,
sm.reason_code,
sm.team_leader_ldap,
sm.return_type,
sm.shipment_status_code,
sm.shipment_rvp_pk_number_of_attempts
