INSERT OVERWRITE TABLE qc_variance_details_l1_hive_fact
select 
qc_verif.inventory_item_id,
qc_verif.warehouse_company,
qc_verif.pv_bucket,
qc_verif.pv_id, 
qc_verif.quantity,
qc_verif.initial_pv_reasons,
qc_verif.initial_pv_sub_reasons,
qc_verif.initial_pv_reasons_desc,
qc_verif.initial_pv_sub_reasons_desc,
qc_verif.initial_pv_done_by,
qc_verif.detailed_pv_reasons,
qc_verif.detailed_pv_sub_reasons,
qc_verif.detailed_pv_reasons_desc,
qc_verif.detailed_pv_sub_reasons_desc,
qc_verif.detailed_pv_done_by,
qc_verif.re_pv_reasons,
qc_verif.re_pv_sub_reasons,
qc_verif.re_pv_reasons_desc,
qc_verif.re_pv_sub_reasons_desc,
qc_verif.re_pv_done_by,
qc_verif.external_inspection_reasons,
qc_verif.external_inspection_sub_reasons,
qc_verif.external_inspection_reasons_desc,
qc_verif.external_inspection_sub_reasons_desc,
qc_verif.external_inspection_done_by,
qc_verif.created_at,
qc_verif.qc_ticket_item_created_date_key,
qc_verif.qc_ticket_item_created_time_key,
qc_verif.initial_pv_updated_at,
qc_verif.initial_pv_updated_date_key,
qc_verif.initial_pv_updated_time_key,
qc_verif.detailed_pv_updated_at,
qc_verif.detailed_pv_updated_date_key,
qc_verif.detailed_pv_updated_time_key,
qc_verif.re_pv_updated_at,
qc_verif.re_pv_updated_date_key,
qc_verif.re_pv_updated_time_key,
qc_verif.external_inspection_updated_at,
qc_verif.external_inspection_updated_date_key,
qc_verif.external_inspection_updated_time_key,
qc_verif.shipment_item_id, 
qc_verif.mr_putlist_item_id as ti_entity_id,
qc_verif.pi_id_min ,
qc_verif.pi_id_max , 
qc_verif.putlist_id_min , 
qc_verif.putlist_id_max ,
qc_verif.mri_movement_request_item_id_min ,
qc_verif.mri_movement_request_item_id_max ,
qc_verif.putlist_creation_time_min ,
qc_verif.putlist_creation_date_min_key,
qc_verif.putlist_creation_time_min_key,
qc_verif.putlist_creation_time_max,
qc_verif.putlist_creation_date_max_key,
qc_verif.putlist_creation_time_max_key,
qc_verif.putlist_created_by,
--qc_verif.putaway_time_min,
--qc_verif.putaway_date_min_key,
--qc_verif.putaway_time_min_key,
--qc_verif.putaway_time_max,
--qc_verif.putaway_date_max_key,
--qc_verif.putaway_time_max_key,
qc_verif.mr_source_type_min,
qc_verif.mr_destination_type_min,
qc_verif.mr_source_type_max,
qc_verif.mr_destination_type_max,
--inv_item.inventory_item_id,
inv_item.inventory_item_storage_location_id,
inv_item.inventory_item_storage_location_id_key,
inv_item.inventory_item_quantity,
inv_item.inventory_item_created_timestamp,
inv_item.inventory_item_created_date_key,
inv_item.inventory_item_created_time_key,
inv_item.inventory_item_updated_at,
inv_item.inventory_item_updated_date_key,
inv_item.inventory_item_updated_time_key,
inv_item.inventory_item_warehouse_id,
inv_item.inventory_item_wid,
inv_item.inventory_item_grn_id,
inv_item.inventory_item_wh_serial_number_id ,
inv_item.wsn_display_id, 
inv_item.inventory_item_storage_location_type, 
inv_item.serial_number,
inv_item.free_text_comment,
inv_item.add_access_comment,
inv_item.prexo_imei_sl_number_received,
inv_item.prexo_brand_received,
inv_item.prexo_model_received,
inv_item.prexo_initial_imei_sl_number_captured,
inv_item.prexo_initial_brand_captured,
inv_item.prexo_initial_model_captured,
inv_item.product_detail_hive_dim_key,
inv_item.inventory_item_storage_location_min_id        ,
inv_item.inventory_item_storage_location_max_id        ,
inv_item.inventory_item_storage_location_min_id_key    ,
inv_item.inventory_item_storage_location_max_id_key    ,
inv_item.wh_storage_location_min                       ,
inv_item.wh_storage_location_max                       ,
inv_item.variance_inventory_item_id,
inv_item.variance_reason_dim_key,
inv_item.variance_quantity,
inv_item.variance_created_at,
inv_item.variance_created_date_key,
inv_item.variance_created_time_key,
inv_item.variance_wid,
inv_item.variance_warehouse_id,
inv_item.variance_id,
inv_item.variance_created_by,
inv_item.variance_storage_location_dim_key,
inv_item.variance_warehouse_dim_key,
inv_item.iiv_product_detail_hive_dim_key,
inv_item.product_id_key,
inv_item.product_fsn,
inv_item.product_listing_id,
inv_item.product_id,
qc_verif.pv_max_numdate,
qc_verif.pv_max_num_date_key,
qc_verif.pv_max_num_time_key,
qc_verif.initial_pv_created_at,
qc_verif.initial_pv_created_date_key,
qc_verif.initial_pv_created_time_key,
qc_verif.detail_pv_created_at,
qc_verif.detail_pv_created_date_key,
qc_verif.detail_pv_created_time_key,
qc_verif.mr_status_min,
qc_verif.mr_status_max,
qc_verif.putaway_updated_at_min,
qc_verif.putaway_updated_at_date_min_key,
qc_verif.putaway_updated_at_time_min_key,
qc_verif.putaway_updated_at_max,
qc_verif.putaway_updated_at_date_max_key,
qc_verif.putaway_updated_at_time_max_key,
inv_item.Prexo_initial_vertical_captured,
inv_item.Prexo_initial_vertical_type_captured,
inv_item.Prexo_initial_title_captured,
inv_item.Prexo_initial_box_psn_captured
from
(
select 
Qc_group.inventory_item_id,
Qc_group.warehouse_company,
Qc_group.PV_Bucket,
Qc_group.pv_id, --added newly
Qc_group.quantity,
Qc_group.Initial_PV_Reasons,
Qc_group.Initial_PV_Sub_Reasons,
Qc_group.Initial_PV_Reasons_desc,
Qc_group.Initial_PV_Sub_Reasons_desc,
Qc_group.initial_pv_done_by,
Qc_group.Detailed_PV_Reasons,
Qc_group.Detailed_PV_Sub_Reasons,
Qc_group.Detailed_PV_Reasons_desc,
Qc_group.Detailed_PV_Sub_Reasons_desc,
Qc_group.Detailed_pv_done_by,
Qc_group.RE_PV_Reasons,
Qc_group.RE_PV_Sub_Reasons,
Qc_group.RE_PV_Reasons_desc,
Qc_group.RE_PV_Sub_Reasons_desc,
Qc_group.RE_PV_done_by,
Qc_group.external_inspection_Reasons,
Qc_group.external_inspection_Sub_Reasons,
Qc_group.external_inspection_Reasons_desc,
Qc_group.external_inspection_Sub_Reasons_desc,
Qc_group.external_inspection_done_by,
Qc_group.created_at,
Qc_group.qc_ticket_item_created_date_key,
Qc_group.qc_ticket_item_created_time_key,
Qc_group.Initial_PV_updated_at,
Qc_group.Initial_PV_updated_date_key,
Qc_group.initial_pv_updated_time_key,
Qc_group.Detailed_PV_updated_at,
Qc_group.Detailed_PV_updated_date_key,
Qc_group.Detailed_pv_updated_time_key,
Qc_group.RE_PV_updated_at,
Qc_group.RE_PV_updated_date_key,
Qc_group.RE_PV_updated_time_key,
Qc_group.external_inspection_updated_at,
Qc_group.external_inspection_updated_date_key,
Qc_group.external_inspection_updated_time_key,
Qc_group.shipment_item_id, -- Newly Added
Qc_group.pv_max_numdate,
Qc_group.pv_max_num_date_key,
Qc_group.pv_max_num_time_key,
--mr.ti_entity_id,
mr.pi_id_min , -- pi_id_min
mr.pi_id_max , -- pi_id_max
mr.putlist_id_min , -- putlist_id_min
mr.putlist_id_max , -- putlist_id_max
mr.mri_movement_request_item_id_min ,
mr.mri_movement_request_item_id_max ,
cast(mr.putlist_creation_time_min as timestamp) as putlist_creation_time_min ,
mr.putlist_creation_date_min_key,
mr.putlist_creation_time_min_key,
cast(mr.putlist_creation_time_max as timestamp) as putlist_creation_time_max,
mr.putlist_creation_date_max_key,
mr.putlist_creation_time_max_key,
mr.putlist_created_by,
mr.putaway_updated_at_min,
mr.putaway_updated_at_max,
mr.putaway_updated_at_date_min_key,
mr.putaway_updated_at_date_max_key,
mr.putaway_updated_at_time_min_key,
mr.putaway_updated_at_time_max_key,
mr.mr_source_type_min,
mr.mr_destination_type_min,
mr.mr_source_type_max,
mr.mr_destination_type_max,
mr.mr_putlist_item_id,
Qc_group.initial_pv_created_at,
Qc_group.initial_pv_created_date_key,
Qc_group.initial_pv_created_time_key,
Qc_group.detail_pv_created_at,
Qc_group.detail_pv_created_date_key,
Qc_group.detail_pv_created_time_key,
mr.mr_status_min,
mr.mr_status_max
from
(
select a.inventory_item_id,
a.warehouse_company,
max(a.id) as PV_id,
max(if(a.qc_verification_reason='seal','detailed_pv',a.qc_verification_reason)) as PV_Bucket,
max(if(a.id is not null,1,0)) as quantity,
max(if(a.qc_type='initial_pv',a.qc_verification_reason,null)) as Initial_PV_Reasons,
max(if(a.qc_type='initial_pv',a.qc_verification_sub_reason,null)) as Initial_PV_Sub_Reasons,
max(if(a.qc_type='initial_pv',a.qc_reason_description,null)) as Initial_PV_Reasons_desc,
max(if(a.qc_type='initial_pv',a.qc_sub_reason_description,null)) as Initial_PV_Sub_Reasons_desc,
max(if(a.qc_type='initial_pv',a.updated_by,null)) as initial_pv_done_by,
max(if(a.qc_type='detailed_pv',a.qc_verification_reason,null)) as Detailed_PV_Reasons,
max(if(a.qc_type='detailed_pv',a.qc_verification_sub_reason,null)) as Detailed_PV_Sub_Reasons,
max(if(a.qc_type='detailed_pv',a.qc_reason_description,null)) as Detailed_PV_Reasons_desc,
max(if(a.qc_type='detailed_pv',a.qc_sub_reason_description,null)) as Detailed_PV_Sub_Reasons_desc,
max(if(a.qc_type='detailed_pv',a.updated_by,null)) as Detailed_pv_done_by,
max(if(a.qc_type='re_pv',a.qc_verification_reason,null)) as RE_PV_Reasons,
max(if(a.qc_type='re_pv',a.qc_verification_sub_reason,null)) as RE_PV_Sub_Reasons,
max(if(a.qc_type='re_pv',a.qc_reason_description,null)) as RE_PV_Reasons_desc,
max(if(a.qc_type='re_pv',a.qc_sub_reason_description,null)) as RE_PV_Sub_Reasons_desc,
max(if(a.qc_type='re_pv',a.updated_by,null)) as RE_PV_done_by,
max(if(a.qc_type='external_inspection',a.qc_verification_reason,null)) as external_inspection_Reasons,
max(if(a.qc_type='external_inspection',a.qc_verification_sub_reason,null)) as external_inspection_Sub_Reasons,
max(if(a.qc_type='external_inspection',a.qc_reason_description,null)) as external_inspection_Reasons_desc,
max(if(a.qc_type='external_inspection',a.qc_sub_reason_description,null)) as external_inspection_Sub_Reasons_desc,
max(if(a.qc_type='external_inspection',a.updated_by,null)) as external_inspection_done_by,
min(a.created_at) created_at,
min(a.qc_ticket_item_created_date_key) as qc_ticket_item_created_date_key,
min(a.qc_ticket_item_created_time_key) as qc_ticket_item_created_time_key,
max(if(a.qc_type='initial_pv',a.updated_at,null)) as Initial_PV_updated_at,
max(if(a.qc_type='initial_pv',a.qc_ticket_item_updated_date_key,null)) as Initial_PV_updated_date_key,
max(if(a.qc_type='initial_pv',a.qc_ticket_item_updated_time_key,null)) as initial_pv_updated_time_key,
max(if(a.qc_type='detailed_pv',a.updated_at,null)) as Detailed_PV_updated_at,
max(if(a.qc_type='detailed_pv',a.qc_ticket_item_updated_date_key,null)) as Detailed_PV_updated_date_key,
max(if(a.qc_type='detailed_pv',a.qc_ticket_item_updated_time_key,null)) as Detailed_pv_updated_time_key,
max(if(a.qc_type='re_pv',a.updated_at,null)) as RE_PV_updated_at,
max(if(a.qc_type='re_pv',a.qc_ticket_item_updated_date_key,null)) as RE_PV_updated_date_key,
max(if(a.qc_type='re_pv',a.qc_ticket_item_updated_time_key,null)) as RE_PV_updated_time_key,
max(if(a.qc_type='external_inspection',a.updated_at,null)) as external_inspection_updated_at,
max(if(a.qc_type='external_inspection',a.qc_ticket_item_updated_date_key,null)) as external_inspection_updated_date_key,
max(if(a.qc_type='external_inspection',a.qc_ticket_item_updated_time_key,null)) as external_inspection_updated_time_key,
max(a.shipment_item_id) as shipment_item_id,
max(a.updated_at) as pv_max_numdate,
max(a.qc_ticket_item_updated_date_key) as pv_max_num_date_key,
max(a.qc_ticket_item_updated_time_key) as pv_max_num_time_key,
---
max(if(a.qc_type='initial_pv',a.created_at,null)) as initial_pv_created_at,
max(if(a.qc_type='initial_pv',a.qc_ticket_item_created_date_key,null)) as initial_pv_created_date_key,
max(if(a.qc_type='initial_pv',a.qc_ticket_item_created_time_key,null)) as initial_pv_created_time_key,

max(if(a.qc_type='detailed_pv',a.created_at,null)) as detail_pv_created_at,
max(if(a.qc_type='detailed_pv',a.qc_ticket_item_created_date_key,null)) as detail_pv_created_date_key,
max(if(a.qc_type='detailed_pv',a.qc_ticket_item_created_time_key,null)) as detail_pv_created_time_key
----
from bigfoot_external_neo.scp_warehouse__fc_qc_ticket_item_l0_hive_fact a
where a.qc_type IN ('re_pv','detailed_pv','external_inspection','initial_pv')
--where a.qc_ticket_item_created_date_key>20160201
group by inventory_item_id,warehouse_company
) Qc_group
left join
(
select 
putlistmin.ti_inventory_item_id ,
main.warehouse_company as warehouse_company,
putlistmax.ti_inventory_item_id as ti_entity_id_1,
putlistmin.ti_task_id as pi_id_min, 
putlistmax.ti_task_id as pi_id_max,
putlistmin.mr_movement_request_id as putlist_id_min,
putlistmax.mr_movement_request_id as putlist_id_max,
putlistmin.mri_movement_request_item_id as mri_movement_request_item_id_min,
putlistmax.mri_movement_request_item_id as mri_movement_request_item_id_max,
putlistmin.mr_created_at as putlist_creation_time_min,
putlistmax.mr_created_at as putlist_creation_time_max,
putlistmin.mr_created_date_key as putlist_creation_date_min_key,
putlistmax.mr_created_date_key as putlist_creation_date_max_key,
putlistmin.mr_created_time_key as putlist_creation_time_min_key,
putlistmax.mr_created_time_key as putlist_creation_time_max_key,
putlistmin.mr_created_by as putlist_created_by,
putlistmin.mr_updated_at as putaway_updated_at_min,
putlistmax.mr_updated_at as putaway_updated_at_max,
putlistmin.mr_updated_date_key as putaway_updated_at_date_min_key,
putlistmax.mr_updated_date_key as putaway_updated_at_date_max_key,
putlistmin.mr_updated_time_key as putaway_updated_at_time_min_key,
putlistmax.mr_updated_time_key as putaway_updated_at_time_max_key,
putlistmin.mr_source_type as mr_source_type_min,
putlistmax.mr_source_type as mr_source_type_max,
putlistmin.mr_destination_type as mr_destination_type_min,
putlistmax.mr_destination_type as mr_destination_type_max,
putlistmax.ti_entity_id as mr_putlist_item_id,
putlistmin.mr_status as mr_status_min,
putlistmax.mr_status as mr_status_max
from
(
select
ti_inventory_item_id as inventory_item_id,
company as warehouse_company,
cast(min(ti_task_id) as string) as pi_id_min , 
cast(max(ti_task_id) as string)as pi_id_max , 
cast(min(mr_movement_request_id) as string) as putlist_id_min , 
cast(max(mr_movement_request_id) as string) as putlist_id_max 
from bigfoot_external_neo.scp_warehouse__fc_movement_request_unit_l0_hive_fact
where mr_type='putlist'
group by ti_inventory_item_id,company
) main
join bigfoot_external_neo.scp_warehouse__fc_movement_request_unit_l0_hive_fact putlistmin  on  (main.inventory_item_id=putlistmin.ti_inventory_item_id and main.putlist_id_min=putlistmin.mr_movement_request_id and main.warehouse_company=putlistmin.company and putlistmin.mr_type='putlist')
join bigfoot_external_neo.scp_warehouse__fc_movement_request_unit_l0_hive_fact putlistmax  on  (main.inventory_item_id=putlistmax.ti_inventory_item_id and main.putlist_id_max=putlistmax.mr_movement_request_id and main.warehouse_company=putlistmax.company and putlistmax.mr_type='putlist')
) mr  on (qc_group.inventory_item_id=mr.ti_inventory_item_id and qc_group.warehouse_company=mr.warehouse_company)
) qc_verif left join 
(
select 
ii.inventory_item_id,
ii.warehouse_company,
ii.inventory_item_storage_location_id,
ii.inventory_item_storage_location_id_key,
ii.inventory_item_quantity,
ii.inventory_item_created_timestamp,
ii.inventory_item_created_date_key,
ii.inventory_item_created_time_key,
ii.inventory_item_updated_at,
ii.inventory_item_updated_date_key,
ii.inventory_item_updated_time_key,
ii.inventory_item_warehouse_id,
ii.inventory_item_wid,
ii.inventory_item_grn_id,
ii.inventory_item_wh_serial_number_id ,
ii.wsn_display_id, -- Added Newly
ii.inventory_item_storage_location_type, 
ii.product_id_key,
ii.product_fsn,
ii.product_listing_id,
ii.product_id,
wsn_psn.serial_number,
wsn_psn.Free_text_comment,
wsn_psn.Add_access_comment,
wsn_psn.prexo_imei_sl_number_received,
wsn_psn.prexo_brand_received,
wsn_psn.prexo_model_received,
wsn_psn.prexo_initial_imei_sl_number_captured,
wsn_psn.prexo_initial_brand_captured,
wsn_psn.prexo_initial_model_captured,
wsn_psn.Prexo_initial_vertical_captured,
wsn_psn.Prexo_initial_vertical_type_captured,
wsn_psn.Prexo_initial_title_captured,
wsn_psn.Prexo_initial_box_psn_captured,
lookupkey('product_detail_wid',ii.inventory_item_wid) as product_detail_hive_dim_key,
str.inventory_item_storage_location_min_id        ,
str.inventory_item_storage_location_max_id        ,
str.inventory_item_storage_location_min_id_key    ,
str.inventory_item_storage_location_max_id_key    ,
str.wh_storage_location_min                       ,
str.wh_storage_location_max                       ,
vi.variance_inventory_item_id,
vi.variance_reason_dim_key,
vi.variance_quantity,
vi.variance_created_at,
vi.variance_created_date_key,
vi.variance_created_time_key,
vi.variance_wid,
vi.variance_warehouse_id,
vi.variance_id,
vi.variance_created_by,
vi.variance_storage_location_dim_key,
vi.variance_warehouse_dim_key,
lookupkey('product_detail_wid',vi.variance_wid) as iiv_product_detail_hive_dim_key
from bigfoot_external_neo.scp_warehouse__fc_inventory_item_l0_hive_fact ii
left join 
(
select wh_serial_number_id,
warehouse_company,
concat_ws(",",collect_list(case when attribute_name='serial_number' then  attribute_value else null end)) as serial_number,
concat_ws(",",collect_list(case when attribute_name='wsn_pv_comments' then  attribute_value else null end)) as Free_text_comment,
concat_ws(",",collect_list(case when attribute_name='add_excess' then  attribute_value else null end)) as Add_access_comment,
concat_ws(",",collect_list(case when attribute_name in ('IMEI_No','Laptop_Serial_No') then  attribute_value else null end)) as Prexo_IMEI_SL_number_received,
concat_ws(",",collect_list(case when attribute_name='brand' then  attribute_value else null end)) as Prexo_brand_received,
concat_ws(",",collect_list(case when attribute_name='model' then  attribute_value else null end)) as Prexo_model_received,
concat_ws(",",collect_list(case when attribute_name in ('Laptop_Serial_No_existing','IMEI_No_existing') then  attribute_value else null end)) as Prexo_Initial_IMEI_SL_number_captured,
concat_ws(",",collect_list(case when attribute_name='brand_existing' then  attribute_value else null end)) as Prexo_initial_brand_captured,
concat_ws(",",collect_list(case when attribute_name='model_existing' then  attribute_value else null end)) as Prexo_initial_model_captured,
concat_ws(",",collect_list(case when attribute_name='product_vertical' then  attribute_value else null end)) as Prexo_initial_vertical_captured,
concat_ws(",",collect_list(case when attribute_name='prexo_vertical_type' then  attribute_value else null end)) as Prexo_initial_vertical_type_captured,
concat_ws(",",collect_list(case when attribute_name='title_existing' then  attribute_value else null end)) as Prexo_initial_title_captured,
concat_ws(",",collect_list(case when attribute_name='box_psn' then  attribute_value else null end)) as Prexo_initial_box_psn_captured

from bigfoot_external_neo.scp_warehouse__fc_wsn_psn_mapping_l0_hive_fact
where is_valid=1
group by wh_serial_number_id,warehouse_company
) wsn_psn on (ii.inventory_item_wh_serial_number_id=wsn_psn.wh_serial_number_id and ii.warehouse_company=wsn_psn.warehouse_company)
left outer join 
(
select 
main.inventory_item_id as inventory_item_id,
main.warehouse_company as warehouse_company,
main.inventory_item_storage_location_id as inventory_item_storage_location_min_id,
main.inventory_item_storage_location_id_key as inventory_item_storage_location_min_id_key,
main.inventory_item_storage_location_id as inventory_item_storage_location_max_id,
main.inventory_item_storage_location_id_key as inventory_item_storage_location_max_id_key,
main.inventory_item_storage_location_type as wh_storage_location_min,
main.inventory_item_storage_location_type as wh_storage_location_max
from
bigfoot_external_neo.scp_warehouse__fc_inventory_item_l0_hive_fact main
left join bigfoot_external_neo.scp_warehouse__fc_inbound_receiving_l0_hive_fact BC
ON (main.inventory_item_grn_id=BC.grn_id AND main.warehouse_company=BC.warehouse_company)
where BC.grn_document_type='shipment'
) str on (ii.inventory_item_id=str.inventory_item_id and ii.warehouse_company=str.warehouse_company) 
left join 
(
select 
v.variance_inventory_item_id,
v.variance_company,
max(v.variance_reason_dim_key) as variance_reason_dim_key,
max(v.variance_quantity) as variance_quantity,-- RVP
max(v.variance_wid) as variance_wid,-- RVP
max(v.variance_warehouse_id) as variance_warehouse_id,-- RVP
max(v.variance_id) as variance_id,-- RVP
max(v.variance_created_by) as variance_created_by,-- RVP
max(v.variance_storage_location_dim_key) as variance_storage_location_dim_key, -- RVP
max(v.variance_warehouse_dim_key) as variance_warehouse_dim_key,
max(v.variance_created_at) as variance_created_at,-- RVP
max(v.variance_created_date_key) as variance_created_date_key,-- RVP
max(v.variance_created_time_key) as variance_created_time_key-- RVP
from bigfoot_external_neo.scp_warehouse__fc_variance_item_hive_l0_fact v
group by v.variance_inventory_item_id,v.variance_company
) vi on (ii.inventory_item_id=vi.variance_inventory_item_id and ii.warehouse_company=vi.variance_company)
) inv_item on (qc_verif.inventory_item_id=inv_item.inventory_item_id and qc_verif.warehouse_company=inv_item.warehouse_company)
