INSERT OVERWRITE TABLE fc_outbound_requests_l0_hive_fact 
SELECT 
t1.outbound_request_company,
t1.outbound_request_shipment_id,
t1.outbound_request_created_at,
t1.outbound_request_created_by,
t1.outbound_request_destination_party_id,
t1.outbound_request_destination_party_type,
t1.outbound_request_external_id,
t1.outbound_request_id,
t1.outbound_request_type,
t1.outbound_request_status,
t1.outbound_request_updated_at,
t1.outbound_request_warehouse_id,
t1.outbound_request_created_date_key,
t1.outbound_request_created_time_key,
t1.outbound_request_updated_date_key,
t1.outbound_request_updated_time_key,
t1.outbound_request_warehouse_dim_key,
t1.ta_pickup_date_key, 
t1.ta_pickup_time_key,
t1.ta_expected_delivery_date_key, 
t1.ta_expected_delivery_time_key,
t1.ta_created_date_key, 
t1.ta_created_time_key,
t1.ta_updated_date_key, 
t1.ta_updated_time_key,
t1.ta_requested_by,
t1.ta_vendor_name,
t1.ta_id,
t1.ta_tracking_id,
t1.ta_warehouse_id
from 
(
SELECT 'fki' as outbound_request_company,
obr.`data`.consignment_id as outbound_request_shipment_id,
from_unixtime(unix_timestamp(obr.`data`.created_at)) as outbound_request_created_at,
obr.`data`.created_by as outbound_request_created_by,
obr.`data`.destination_party_id as outbound_request_destination_party_id,
obr.`data`.destination_party_type as outbound_request_destination_party_type,
obr.`data`.external_id as outbound_request_external_id,
obr.`data`.id as outbound_request_id,
obr.`data`.outbound_request_type as outbound_request_type,
obr.`data`.status as outbound_request_status,
from_unixtime(unix_timestamp(obr.`data`.updated_at)) as outbound_request_updated_at,
obr.`data`.warehouse_id as outbound_request_warehouse_id,
lookup_date(obr.`data`.created_at) as outbound_request_created_date_key,
lookup_time(obr.`data`.created_at) as outbound_request_created_time_key,
lookup_date(obr.`data`.updated_at) as outbound_request_updated_date_key,
lookup_time(obr.`data`.updated_at) as outbound_request_updated_time_key,
lookupkey('warehouse_id',obr.`data`.warehouse_id) as outbound_request_warehouse_dim_key,
--transport attribute
lookup_date(ta.`data`.pickup_date) as ta_pickup_date_key, 
lookup_time(ta.`data`.pickup_date) as ta_pickup_time_key,
lookup_date(ta.`data`.expected_delivery_date) as ta_expected_delivery_date_key, 
lookup_time(ta.`data`.expected_delivery_date) as ta_expected_delivery_time_key,
lookup_date(ta.`data`.created_at) as ta_created_date_key, 
lookup_time(ta.`data`.created_at) as ta_created_time_key,
lookup_date(ta.`data`.updated_at) as ta_updated_date_key, 
lookup_time(ta.`data`.updated_at) as ta_updated_time_key,
ta.`data`.requested_by as ta_requested_by,
ta.`data`.vendor_name as ta_vendor_name,
ta.`data`.id as ta_id,
ta.`data`.tracking_id as ta_tracking_id,
ta.`data`.warehouse_id as ta_warehouse_id
FROM bigfoot_snapshot.dart_fki_scp_warehouse_outbound_request_1_view_total obr
left join bigfoot_snapshot.dart_fki_scp_warehouse_transport_attribute_1_view_total ta
on obr.`data`.id = ta.`data`.entity_id

union all

SELECT 'wsr' as outbound_request_company,
obr.`data`.consignment_id as outbound_request_shipment_id,
from_unixtime(unix_timestamp(obr.`data`.created_at)) as outbound_request_created_at,
obr.`data`.created_by as outbound_request_created_by,
obr.`data`.destination_party_id as outbound_request_destination_party_id,
obr.`data`.destination_party_type as outbound_request_destination_party_type,
obr.`data`.external_id as outbound_request_external_id,
obr.`data`.id as outbound_request_id,
obr.`data`.outbound_request_type as outbound_request_type,
obr.`data`.status as outbound_request_status,
from_unixtime(unix_timestamp(obr.`data`.updated_at)) as outbound_request_updated_at,
obr.`data`.warehouse_id as outbound_request_warehouse_id,
lookup_date(obr.`data`.created_at) as outbound_request_created_date_key,
lookup_time(obr.`data`.created_at) as outbound_request_created_time_key,
lookup_date(obr.`data`.updated_at) as outbound_request_updated_date_key,
lookup_time(obr.`data`.updated_at) as outbound_request_updated_time_key,
lookupkey('warehouse_id',obr.`data`.warehouse_id) as outbound_request_warehouse_dim_key,
--transport attribute
lookup_date(ta.`data`.pickup_date) as ta_pickup_date_key, 
lookup_time(ta.`data`.pickup_date) as ta_pickup_time_key,
lookup_date(ta.`data`.expected_delivery_date) as ta_expected_delivery_date_key, 
lookup_time(ta.`data`.expected_delivery_date) as ta_expected_delivery_time_key,
lookup_date(ta.`data`.created_at) as ta_created_date_key, 
lookup_time(ta.`data`.created_at) as ta_created_time_key,
lookup_date(ta.`data`.updated_at) as ta_updated_date_key, 
lookup_time(ta.`data`.updated_at) as ta_updated_time_key,
ta.`data`.requested_by as ta_requested_by,
ta.`data`.vendor_name as ta_vendor_name,
ta.`data`.id as ta_id,
ta.`data`.tracking_id as ta_tracking_id,
ta.`data`.warehouse_id as ta_warehouse_id
FROM bigfoot_snapshot.dart_wsr_scp_warehouse_outbound_request_1_view_total obr
left join bigfoot_snapshot.dart_wsr_scp_warehouse_transport_attribute_1_view_total ta
on obr.`data`.id = ta.`data`.entity_id) t1;
