Insert Overwrite table fulfillment_liteshipmentitems_base_fact
select shipment_items.shipment_item_sr_id ,
shipment_items.sr_id,
shipment_items.cms_category,
shipment_items.cms_vertical,
shipment_items.created_at,
shipment_items.invoice_number,
shipment_items.item_content,
shipment_items.listing_breadth,
shipment_items.listing_height,
shipment_items.listing_length,
shipment_items.listing_weight,
shipment_items.lpe_tier,
shipment_items.order_id,
shipment_items.order_item_id,
shipment_items.product_currency,
shipment_items.product_value,
shipment_items.product_breadth,
shipment_items.product_height,
shipment_items.product_length,
shipment_items.product_weight,
shipment_items.product_id,
shipment_items.product_title,
shipment_items.quantity,
shipment_items.seller_pincode,
shipment_items.seller_id,
shipment_items.seller_type,
shipment_items.tax_per_unit_currency,
shipment_items.tax_per_unit_value,
shipment_items.total_tax_currency,
shipment_items.total_tax_value,
count(distinct case when shipment_items.handling_attributes='dangerous' then shipment_items.shipment_item_sr_id else null end) as is_dangerous

from (
select entityid as shipment_item_sr_id ,
`data`.associated_sr_id as sr_id,
`data`.cms_category as cms_category,
`data`.cms_vertical as cms_vertical,
`data`.created_at as created_at,
 handling_attributes,
`data`.invoice_number as invoice_number,
`data`.item_content as item_content,
`data`.listing_dimension.breadth as listing_breadth,
`data`.listing_dimension.height as listing_height,
`data`.listing_dimension.length as listing_length,
`data`.listing_dimension.weight as listing_weight,
`data`.lpe_tier as lpe_tier,
`data`.order_id as order_id,
`data`.order_item_id as order_item_id,
`data`.product_cost.currency as product_currency,
`data`.product_cost.value as product_value,
`data`.product_dimension.breadth as product_breadth,
`data`.product_dimension.height as product_height,
`data`.product_dimension.length as product_length,
`data`.product_dimension.weight as product_weight,
`data`.product_id as product_id,
`data`.product_title as product_title,
`data`.quantity as quantity,
`data`.seller.pincode as seller_pincode,
`data`.seller.seller_id as seller_id,
`data`.seller.type as seller_type,
`data`.tax_per_unit.currency as tax_per_unit_currency,
`data`.tax_per_unit.value as tax_per_unit_value,
`data`.total_tax.currency as total_tax_currency,
`data`.total_tax.value as total_tax_value 
from bigfoot_snapshot.dart_fkint_scp_fulfillment_liteshipmentitems_5_view lateral view outer explode  (`data`.handling_attributes) table_ha as handling_attributes )  shipment_items
 group by shipment_items.shipment_item_sr_id ,
shipment_items.sr_id,
shipment_items.cms_category,
shipment_items.cms_vertical,
shipment_items.created_at,
shipment_items.invoice_number,
shipment_items.item_content,
shipment_items.listing_breadth,
shipment_items.listing_height,
shipment_items.listing_length,
shipment_items.listing_weight,
shipment_items.lpe_tier,
shipment_items.order_id,
shipment_items.order_item_id,
shipment_items.product_currency,
shipment_items.product_value,
shipment_items.product_breadth,
shipment_items.product_height,
shipment_items.product_length,
shipment_items.product_weight,
shipment_items.product_id,
shipment_items.product_title,
shipment_items.quantity,
shipment_items.seller_pincode,
shipment_items.seller_id,
shipment_items.seller_type,
shipment_items.tax_per_unit_currency,
shipment_items.tax_per_unit_value,
shipment_items.total_tax_currency,
shipment_items.total_tax_value;
