INSERT OVERWRITE TABLE qc_liquidation_l2_hive_fact
select distinct
si.shipment_item_id,
si.shipment_display_id,
si.shipment_id,
si.shipment_return_warehouse_id,
si.shipment_entity_type as shipment_type,-- need to check
si.shipment_destination_type, -- need to check
si.box_tracking_id as shipment_tracking_id,
si.box_outer_used_packing_box_id as shipment_box_used_packing_box_id,
--if(si.shipment_status='received','rvp','rto') as Wh_RVP_RTO_flag,
if(si.shipment_status='received','rvp',if(si.shipment_status='returned','rto','pending_RC_in')) as Wh_RVP_RTO_flag,
si.shipment_status, -- Newly Added
if(shipment_status in ('received','returned'),shimpment_created_date_key,shimpment_created_date_key) as shipment_received_date_key,
si.shipment_item_status,
si.shipment_item_quantity,
si.shipment_courier_name, -- need to check
si.shipment_item_is_excess,
si.shipment_is_tampered,
si.shipment_warehouse_id as warehouse_id,
si.shipment_item_order_item_id,
si.shipment_item_quantity_received               ,
si.shipment_item_quantity_lost_during_dispatch   ,
si.shipment_item_quantity_packed                 ,
si.shipment_item_product_key                     ,
si.shipment_item_updated_timestamp               ,
si.shipment_item_updated_date_key                ,
si.shipment_item_updated_time_key                ,
si.shipment_item_cancelled_timestamp             ,
si.shipment_item_cancelled_date_key              ,
si.shipment_item_cancelled_time_key              ,
si.shimpment_created_timestamp                   ,
si.shimpment_created_date_key                    ,
si.shimpment_created_time_key                    ,
si.shipment_qc_done_timestamp                    ,
si.shipment_qc_done_date_key                     ,
si.shipment_qc_done_time_key                     ,
si.shipment_updated_timestamp                    ,
si.shipment_updated_date_key                     ,
si.shipment_updated_time_key                     ,
si.shipment_cancelled_timestamp                  ,
si.shipment_cancelled_date_key                   ,
si.shipment_cancelled_time_key                   ,
si.shipment_rto_received_timestamp               ,
si.shipment_rto_received_date_key                ,
si.shipment_rto_received_time_key                ,
si.shipment_rvp_received_timestamp               ,
si.shipment_rvp_received_date_key                ,
si.shipment_rvp_received_time_key                ,
si.shipment_rto_mh_scan_timestamp                ,
si.shipment_rto_mh_scan_date_key                 ,
si.shipment_rto_mh_scan_time_key                 ,
si.shipment_rvp_mh_scan_timestamp                ,
si.shipment_rvp_mh_scan_date_key                 ,
si.shipment_rvp_mh_scan_time_key                 ,
si.shipment_dispatched_timestamp                 ,
si.shipment_dispatched_date_key                  ,
si.shipment_dispatched_time_key                  ,
si.shipment_warehouse_dim_key                    ,
si.shipment_ekart_dispatch_by_date               ,
si.shipment_ekart_dispatch_by_date_key           ,
si.shipment_ekart_dispatch_by_time_key           ,
si.shipment_ff_dispatch_by_date                  ,
si.shipment_ff_dispatch_by_date_key              ,
si.shipment_ff_dispatch_by_time_key              ,
si.shipment_packed_timestamp                     ,
si.shipment_packed_date_key                      ,
si.shipment_packed_time_key                      ,
qc_verif.inventory_item_id,
qc_verif.PV_Bucket,
qc_verif.pv_id, 
qc_verif.quantity,
qc_verif.Initial_PV_Reasons,
qc_verif.Initial_PV_Sub_Reasons,
qc_verif.Initial_PV_Reasons_desc,
qc_verif.Initial_PV_Sub_Reasons_desc,
qc_verif.initial_pv_done_by,
qc_verif.Detailed_PV_Reasons,
qc_verif.Detailed_PV_Sub_Reasons,
qc_verif.Detailed_PV_Reasons_desc,
qc_verif.Detailed_PV_Sub_Reasons_desc,
qc_verif.Detailed_pv_done_by,
qc_verif.RE_PV_Reasons,
qc_verif.RE_PV_Sub_Reasons,
qc_verif.RE_PV_Reasons_desc,
qc_verif.RE_PV_Sub_Reasons_desc,
qc_verif.RE_PV_done_by,
qc_verif.external_inspection_Reasons,
qc_verif.external_inspection_Sub_Reasons,
qc_verif.external_inspection_Reasons_desc,
qc_verif.external_inspection_Sub_Reasons_desc,
qc_verif.external_inspection_done_by,
qc_verif.created_at,
qc_verif.qc_ticket_item_created_date_key,
qc_verif.qc_ticket_item_created_time_key,
qc_verif.Initial_PV_updated_at,
qc_verif.Initial_PV_updated_date_key,
qc_verif.initial_pv_updated_time_key,
qc_verif.Detailed_PV_updated_at,
qc_verif.Detailed_PV_updated_date_key,
qc_verif.Detailed_pv_updated_time_key,
qc_verif.RE_PV_updated_at,
qc_verif.RE_PV_updated_date_key,
qc_verif.RE_PV_updated_time_key,
qc_verif.external_inspection_updated_at,
qc_verif.external_inspection_updated_date_key,
qc_verif.external_inspection_updated_time_key,
--qc_verif.shipment_item_id, 
qc_verif.ti_entity_id,
qc_verif.pi_id_min ,
qc_verif.pi_id_max , 
qc_verif.putlist_id_min , 
qc_verif.putlist_id_max ,
qc_verif.mri_movement_request_item_id_min ,
qc_verif.mri_movement_request_item_id_max ,
qc_verif.putlist_creation_time_min ,
qc_verif.putlist_creation_date_min_key,
qc_verif.putlist_creation_time_min_key,
qc_verif.putlist_creation_time_max,
qc_verif.putlist_creation_date_max_key,
qc_verif.putlist_creation_time_max_key,
qc_verif.putlist_created_by,
--qc_verif.putaway_time_min,
--qc_verif.putaway_date_min_key,
--qc_verif.putaway_time_min_key,
--qc_verif.putaway_time_max,
--qc_verif.putaway_date_max_key,
--qc_verif.putaway_time_max_key,
qc_verif.mr_source_type_min,
qc_verif.mr_destination_type_min,
qc_verif.mr_source_type_max,
qc_verif.mr_destination_type_max,
if(qc_verif.wh_storage_location_min='product_missing_bulk' and qc_verif.pv_bucket='mis_shipment', 'Mis-shipment','') as mis_shipment_filter,
--if(grn.return_id is null and si.shipment_status='received','Prexo','') as prexo_filter,
if(grn.return_type='prexo_return','Prexo','') as prexo_filter,
--qc_verif.inventory_item_id,
qc_verif.inventory_item_storage_location_id,
qc_verif.inventory_item_storage_location_id_key,
qc_verif.inventory_item_quantity,
qc_verif.inventory_item_created_timestamp,
qc_verif.inventory_item_created_date_key,
qc_verif.inventory_item_created_time_key,
qc_verif.inventory_item_updated_at,
qc_verif.inventory_item_updated_date_key,
qc_verif.inventory_item_updated_time_key,
qc_verif.inventory_item_warehouse_id,
qc_verif.inventory_item_wid,
qc_verif.inventory_item_grn_id,
qc_verif.inventory_item_wh_serial_number_id ,
qc_verif.wsn_display_id, 
qc_verif.inventory_item_storage_location_type, 
qc_verif.serial_number,
qc_verif.Free_text_comment,
qc_verif.Add_access_comment,
qc_verif.prexo_imei_sl_number_received,
qc_verif.prexo_brand_received,
qc_verif.prexo_model_received,
qc_verif.prexo_initial_imei_sl_number_captured,
qc_verif.prexo_initial_brand_captured,
qc_verif.prexo_initial_model_captured,
qc_verif.product_detail_hive_dim_key,
qc_verif.inventory_item_storage_location_min_id        ,
qc_verif.inventory_item_storage_location_max_id        ,
qc_verif.inventory_item_storage_location_min_id_key    ,
qc_verif.inventory_item_storage_location_max_id_key    ,
qc_verif.wh_storage_location_min                       ,
qc_verif.wh_storage_location_max                       ,
qc_verif.variance_inventory_item_id,
qc_verif.variance_reason_dim_key,
qc_verif.variance_quantity,
qc_verif.variance_created_at,
qc_verif.variance_created_date_key,
qc_verif.variance_created_time_key,
qc_verif.variance_wid,
qc_verif.variance_warehouse_id,
qc_verif.variance_id,
qc_verif.variance_created_by,
qc_verif.variance_storage_location_dim_key,
qc_verif.variance_warehouse_dim_key,
qc_verif.iiv_product_detail_hive_dim_key,
grn.return_item_id as return_item_id,
grn.return_id                     ,
grn.order_item_id                 ,
grn.return_item_quantity          ,
grn.return_item_shipment_id       ,
grn.return_item_tracking_id       ,
grn.courier_name                  ,
grn.return_courier_bucket,
grn.return_quantity_recvd_in_wh    ,
grn.return_quantity_rvp_done       ,
grn.return_item_notional_value    ,
grn.return_reason                  ,
grn.return_quantity_qc_passed      ,
grn.return_quantity_qc_failed      ,
grn.oms_qc_reason                  ,
grn.oms_qc_comment                 ,
grn.tenant_id                      ,
grn.seller_id                      ,
grn.seller_bucket,
grn.return_sub_reason               ,
grn.exchange_fsn_key                ,
grn.exchange_fsn,
grn.return_pickup_promise_date      ,
grn.external_order_id               ,
grn.return_status                   ,
grn.return_to_address_id            ,
grn.return_customer_will_send       ,
grn.return_action                   ,
grn.return_type                     ,
grn.return_request_channel          ,
grn.return_amount                   ,
grn.return_comments                 ,
grn.returned_product_id_key         ,
grn.return_request_date             , 
grn.return_reason_bucket_key                  ,
grn.return_courier_name_key                   ,
grn.seller_id_key                             ,
grn.return_pickup_promise_date_key            ,
grn.return_product_listing_id_key             ,
grn.return_request_date_key                   ,
grn.order_id                        ,        
grn.order_external_id               ,           
grn.order_item_selling_price        ,           
grn.order_item_seller_id            ,           
grn.order_item_seller_id_key        ,           
grn.order_item_quantity             ,                    
grn.order_shipping_address_id_key   ,           
grn.return_item_product_title             ,
grn.return_item_product_id              ,
grn.return_item_product_id_key      ,
grn.return_item_category_id         ,
grn.order_item_type,
grn.order_item_date,
--grn.account_id,
concat('NonFBF_',qc_verif.inventory_item_id) as inventory_item_id_key,
'NonFBF' as flag_fbf_type,
--if(isnull(putaway_area_min),wh_storage_location_area_min,putaway_area_min) as fin_inv_location_min,
if(qc_verif.mr_destination_type_min is null,wh_storage_location_min,qc_verif.mr_destination_type_min) as fin_inv_location_min,
--if(isnull(putaway_area_max),wh_storage_location_area_max,putaway_area_max) as fin_inv_location_max,
if(qc_verif.mr_destination_type_max is null,qc_verif.wh_storage_location_max,qc_verif.mr_destination_type_max) as fin_inv_location_max,
if(qc_verif.putlist_id_min is not null,1,0) as flag_putaway_done,  
if(qc_verif.wh_storage_location_min is not null and qc_verif.putlist_id_min is null,1,0) as flag_storage_location_only,
--if(grn.return_item_tracking_id is null,si.box_tracking_id,grn.return_item_tracking_id) as shipmentid,
if(grn.return_item_shipment_id is null,si.box_tracking_id,grn.return_item_shipment_id) as shipmentid,
qc_verif.product_id_key,
qc_verif.product_fsn,
qc_verif.product_listing_id,
qc_verif.product_id,
si.packing_box_used_outer_name,
si.warehouse_company,
rover.reservation_order_item_id as reservation_order_item_id,
rover.number1 as number1,
rover.number2 as number2,
rover.number3 as number3,
--reser.reservation_inventory_item_id as reservation_inventory_item_id,
qc_verif.pv_max_numdate,
qc_verif.pv_max_num_date_key,
qc_verif.pv_max_num_time_key,
grn.return_numdate,
grn.return_numdate_key,
qc_verif.Prexo_initial_vertical_captured,
qc_verif.Prexo_initial_vertical_type_captured,
qc_verif.Prexo_initial_title_captured,
qc_verif.Prexo_initial_box_psn_captured

from bigfoot_external_neo.scp_ekl__qc_variance_details_l1_hive_fact qc_verif
left outer join bigfoot_external_neo.scp_warehouse__fc_shipment_item_l0_hive_fact si on (si.shipment_item_id=qc_verif.shipment_item_id)
left outer join bigfoot_external_neo.scp_ekl__goods_recon_l2_hive_fact grn on (si.shipment_item_order_item_id=grn.order_item_id and si.shipment_display_id=grn.return_item_tracking_id and grn.return_item_tracking_id is not null)
left outer join
(
select reser.reservation_order_item_id as reservation_order_item_id,
concat_ws("-",collect_set(ser.number1)) as number1,
concat_ws("-",collect_set(ser.number2)) as number2,
concat_ws("-",collect_set(ser.number3)) as number3
from bigfoot_external_neo.scp_warehouse__fc_reservation_l0_hive_fact reser
left outer join 
bigfoot_external_neo.scp_warehouse__fc_product_serial_number_map_l0_hive_fact ser
ON (reser.reservation_inventory_item_id=ser.inventory_item_id)
where ser.is_valid=1
group by reser.reservation_order_item_id
) rover on (si.shipment_item_order_item_id=rover.reservation_order_item_id)
;
