INSERT OVERWRITE TABLE shipment_l1_90_fact
SELECT
	shipment_l0.shipment_id as shipment_id,
	shipment_l0.first_associated_shipment_id as first_associated_shipment_id,
	shipment_l0.vendor_tracking_id AS vendor_tracking_id,
	shipment_l0.merchant_reference_id AS merchant_reference_id,
	shipment_l0.merchant_id AS merchant_id,
	shipment_l0.seller_id AS seller_id,
	shipment_l0.shipment_current_status as shipment_current_status,
	shipment_l0.payment_type as payment_type,
	shipment_l0.payment_mode as payment_mode,
	shipment_l0.pos_id as pos_id,
	shipment_l0.transaction_id as transaction_id,
	shipment_l0.agent_id as agent_id,
	shipment_l0.amount_collected as amount_collected,
	shipment_l0.seller_type as seller_type,
	NULL as packing_box_type,
	shipment_l0.shipment_dg_flag as shipment_dg_flag,
	shipment_l0.shipment_flash_flag as shipment_flash_flag,
	shipment_l0.shipment_fragile_flag as shipment_fragile_flag,
	shipment_l0.shipment_priority_flag as shipment_priority_flag,
	shipment_l0.service_tier as service_tier,
	shipment_l0.surface_mandatory_flag as surface_mandatory_flag,
	shipment_l0.shipment_size_flag as shipment_size_flag,
	shipment_l0.item_quantity as item_quantity,
	shipment_l0.shipping_category as shipping_category,
	shipment_l0.ekl_shipment_type as ekl_shipment_type,
	shipment_l0.reverse_shipment_type as reverse_shipment_type,
	shipment_fl.first_undelivery_status as first_undelivery_status,
	shipment_fl.last_undelivery_status as last_undelivery_status,
	shipment_l0.ekl_fin_zone as ekl_fin_zone,
	shipment_l0.ekart_lzn_flag as ekart_lzn_flag,
	shipment_l0.shipment_fa_flag as shipment_fa_flag,
	shipment_l0.vendor_id AS vendor_id,
	shipment_l0.shipment_carrier as shipment_carrier,
	shipment_l0.shipment_pending_flag as shipment_pending_flag,
	shipment_l0.shipment_num_of_pk_attempt as shipment_num_of_pk_attempt,
	shipment_l0.fsd_number_of_ofd_attempts as fsd_number_of_ofd_attempts,
	shipment_l0.shipment_rvp_pk_number_of_attempts as shipment_rvp_pk_number_of_attempts,
	shipment_l0.shipment_weight as shipment_weight,
	shipment_l0.sender_weight as sender_weight,
	shipment_l0.system_weight as system_weight,
	shipment_l0.volumetric_weight_source as volumetric_weight_source,
	shipment_l0.volumetric_weight as volumetric_weight,
	shipment_l0.billable_weight as billable_weight,
	shipment_l0.billable_weight_type as billable_weight_type,
	shipment_l0.cost_of_breach AS cost_of_breach,
	shipment_l0.shipment_value as shipment_value,
	shipment_l0.cod_amount_to_collect as cod_amount_to_collect,
	shipment_l0.shipment_charge as shipment_charge,
	shipment_l0.source_address_pincode as source_address_pincode,
	shipment_l0.destination_address_pincode as destination_address_pincode,
	shipment_l0.customer_address_id as customer_address_id,
	shipment_l0.cs_notes as cs_notes,
	shipment_l0.hub_notes as hub_notes,
	shipment_fl.fsd_assigned_hub_id as fsd_assigned_hub_id,
	if(shipment_l0.reverse_pickup_hub_id = -1,shipment_fl.reverse_pickup_hub_id,NULL) AS reverse_pickup_hub_id,
	shipment_l0.shipment_current_hub_id,
	shipment_fl.shipment_first_received_hub_id as shipment_first_received_hub_id,
	shipment_fl.shipment_last_received_hub_id as shipment_last_received_hub_id,
	shipment_fl.shipment_first_received_mh_id as shipment_first_received_mh_id,
	shipment_fl.shipment_last_received_mh_id as shipment_last_received_mh_id,
	If(shipment_fl.shipment_first_received_mh_id IS NOT NULL,shipment_fl.shipment_first_received_mh_id,shipment_l0.shipment_origin_mh_facility_id) as shipment_origin_mh_facility_id,
	If(shipment_l0.shipment_destination_mh_facility_id = -1, shipment_fl.shipment_last_received_mh_id , shipment_l0.shipment_destination_mh_facility_id) as shipment_destination_mh_facility_id,
	If(shipment_l0.shipment_origin_facility_id is not null and shipment_l0.shipment_origin_facility_id <>0 , shipment_l0.shipment_origin_facility_id, shipment_fl.shipment_origin_facility_id) as shipment_origin_facility_id,
	shipment_l0.shipment_destination_facility_id as shipment_destination_facility_id ,
	shipment_fl.shipment_first_received_dh_id as shipment_first_received_dh_id ,
	shipment_fl.shipment_last_received_dh_id as shipment_last_received_dh_id,
	shipment_fl.shipment_first_received_pc_id as shipment_first_received_pc_id,
	shipment_fl.shipment_last_received_pc_id as shipment_last_received_pc_id,
	shipment_fl.rto_received_hub_id as rto_received_hub_id,
	shipment_l0.shipment_current_hub_type as shipment_current_hub_type,
	shipment_l0.shipment_created_at_datetime as shipment_created_at_datetime ,
	shipment_l0.shipment_dispatch_datetime as shipment_dispatch_datetime,
	shipment_l0.vendor_dispatch_datetime as vendor_dispatch_datetime,
	shipment_l0.shipment_current_status_datetime as shipment_current_status_datetime,
	shipment_l0.shipment_first_received_at_datetime as shipment_first_received_at_datetime,
	shipment_l0.shipment_delivered_at_datetime as shipment_delivered_at_datetime,
	shipment_l0.shipment_last_delivered_at_datetime as shipment_last_delivered_at_datetime,
	shipment_l0.shipment_first_delivery_update_datetime as shipment_first_delivery_update_datetime,
	shipment_l0.shipment_last_delivery_update_datetime as shipment_last_delivery_update_datetime,
	shipment_l0.shipment_first_dispatched_to_merchant_datetime as shipment_first_dispatched_to_merchant_datetime,
	If(shipment_fl.logistics_promise_datetime is null , shipment_l0.logistics_promise_datetime, cast(shipment_fl.logistics_promise_datetime as TIMESTAMP)),
	shipment_l0.shipment_actual_sla_datetime,
	If(shipment_fl.customer_promise_datetime is null,shipment_l0.customer_promise_datetime,cast(shipment_fl.customer_promise_datetime as timestamp)),
	shipment_l0.new_logistics_promise_datetime as new_logistics_promise_datetime,
	shipment_l0.new_customer_promise_datetime as new_customer_promise_datetime,
	shipment_l0.shipment_last_receive_datetime as shipment_last_receive_datetime,
	shipment_l0.fsd_first_dh_received_datetime as fsd_first_dh_received_datetime,
	shipment_l0.fsd_last_dh_received_datetime as fsd_last_dh_received_datetime,
	shipment_l0.shipment_first_received_pc_datetime as shipment_first_received_pc_datetime,
	shipment_l0.shipment_last_received_pc_datetime as shipment_last_received_pc_datetime,
	shipment_l0.fsd_first_ofd_datetime as fsd_first_ofd_datetime,
	shipment_l0.fsd_last_ofd_datetime as fsd_last_ofd_datetime,
	shipment_l0.shipment_first_rfp_datetime as shipment_first_rfp_datetime,
	shipment_l0.shipment_last_rfp_datetime as shipment_last_rfp_datetime,
	shipment_l0.shipment_first_picksheet_creation_time as shipment_first_picksheet_creation_time,--n
	shipment_l0.shipment_last_picksheet_creation_time as shipment_last_picksheet_creation_time,--n
	shipment_l0.shipment_first_rvp_pickup_time as shipment_first_rvp_pickup_time,
	shipment_l0.shipment_last_rvp_pickup_time as shipment_last_rvp_pickup_time,
	shipment_l0.received_at_origin_facility_datetime as received_at_origin_facility_datetime,
	shipment_l0.rto_first_received_time as rto_first_received_datetime,
	shipment_l0.rto_create_datetime as rto_create_datetime,
	shipment_l0.rto_complete_datetime as rto_complete_datetime,
	shipment_l0.tpl_first_ofd_datetime as tpl_first_ofd_datetime,
	shipment_l0.tpl_last_ofd_datetime as tpl_last_ofd_datetime,
	shipment_l0.first_mh_tc_receive_datetime as first_mh_tc_receive_datetime,
	shipment_l0.last_mh_tc_receive_datetime as last_mh_tc_receive_datetime,
	shipment_l0.first_mh_tc_outscan_datetime as first_mh_tc_outscan_datetime,
	shipment_l0.last_mh_tc_outscan_datetime as last_mh_tc_outscan_datetime,
	shipment_l0.first_dh_outscan_datetime as first_dh_outscan_datetime,
	shipment_l0.last_dh_outscan_datetime as last_dh_outscan_datetime,
	shipment_l0.profiled_hub_id as profiled_hub_id,
	shipment_fl.profiler_flag as profiler_flag,
	shipment_l0.shipment_dispatch_service_tier as shipment_dispatch_service_tier,
	shipment_l0.shipment_dispatch_by_datetime as shipment_dispatch_by_datetime,
	shipment_l0.shipment_lzn_classification as shipment_lzn_classification,
	shipment_l0.shipment_transit_distance as shipment_transit_distance,
	shipment_l0.shipment_transit_time as shipment_transit_time,
	shipment_l0.reverse_complete_datetime as reverse_complete_datetime,
	shipment_l0.pickup_slot_start_datetime,
	shipment_l0.pickup_slot_end_datetime,
	shipment_fl.rto_first_undelivery_status,
	shipment_fl.first_undelivery_status_datetime,
	shipment_fl.last_undelivery_status_datetime,
	shipment_fl.rto_first_undelivery_status_datetime,
	shipment_l0.rto_num_ofd_attempts,
	shipment_l0.shipment_contour_volume,
	shipment_l0.mlo_datetime as myn_logstcs_outscn_datetime
FROM
	bigfoot_external_neo.scp_ekl__shipment_l0_90_fact shipment_l0
LEFT OUTER join
	(
		select shipment_id,
		first_undelivery_status,
		last_undelivery_status,
		reverse_pickup_hub_id,
		shipment_last_received_hub_id,
		shipment_first_received_hub_id,
		shipment_first_received_mh_id,
		shipment_last_received_mh_id,
		shipment_first_received_dh_id,
		shipment_last_received_dh_id,
		logistics_promise_datetime,
		customer_promise_datetime,
		shipment_origin_facility_id,
		shipment_first_received_pc_id,
		shipment_last_received_pc_id,
		rto_received_hub_id,
		fsd_assigned_hub_id,
		rto_first_undelivery_status,
		first_undelivery_status_datetime,
		last_undelivery_status_datetime,
		rto_first_undelivery_status_datetime,
		profiler_flag
		from
		bigfoot_external_neo.scp_ekl__shipment_fl_l0_90_fact 
	) shipment_fl
on shipment_fl.shipment_id=shipment_l0.shipment_id;