INSERT OVERWRITE TABLE first_mile_pickup_request_hive_fact
Select
Distinct
tracking_id,
pickuprequest_id,
mp_pickup_hub_id,
mp_pickup_hub_key,
mp_requested_date_key,
mp_requested_date as mp_requested_date_time,
mp_day,
reqested_hour as mp_reqested_date_hour,
mp_pickup_promise_date,
mp_pickup_compliance,
mp_first_out_for_pickup_date as mp_first_out_for_pickup_date_time,
mp_first_out_for_pickup_date_key,
mp_first_out_for_pickup_time_key,
mp_received_at_origin_date_key,
mp_received_at_origin_date as mp_received_at_origin_date_time,
mp_dispatched_to_tc_date_key,
mp_dispatched_to_tc_date as mp_dispatched_to_tc_date_time,
mp_received_at_tc_date_key,
mp_received_at_tc_date as mp_received_at_tc_date_time,
mp_num_of_pk_attempts,
mp_num_of_pk_reattempts,
current_hub_type,
current_hub_id_key,
mp_current_status,
mp_requested_time_key,
mp_received_at_origin_time_key,
mp_dispatched_to_tc_time_key,
mp_received_at_tc_time_key,
mp_last_out_for_pickup_date as mp_last_out_for_pickup_date_time,
seller_id_key,
lookup_date(mp_pickup_promise_date) as mp_pickup_promise_date_key,
if(G.mp_first_out_for_pickup_date IS NULL,'Not_Attempted',
if(G.mp_received_at_origin_date IS NULL,'Not_picked',
  if(G.mp_dispatched_to_tc_date IS NULL,'Pickup_hub',
    if(G.mp_received_at_tc_date IS NULL,'Intransit_to_tc','Received_at_tc')))) as mp_pending_location,
if(G.mp_num_of_pk_attempts>1,1,0) as reattempt_flag,
if(ISNULL(G.mp_dispatched_to_tc_date),0,1) as mp_dispatch_to_tc_flag,
if(ISNULL(G.mp_received_at_tc_date),0,1) as mp_received_at_tc_flag,
if(ISNULL(G.mp_first_out_for_pickup_date),0,1) as  mp_first_out_for_pickup_flag,
G.rtd_to_picked_days as rtd_to_picked_days,
G.picked_to_dispatch_days as picked_to_dispatch_to_tc_days,
G.dispatched_to_rec_at_tc_days as dispatched_to_rec_at_tc_days,
G.rtd_to_tc_rec_days as rtd_to_tc_rec_days,
G.No_Seller_reattempt as No_Seller_reattempt,
G.No_of_ekl_attempt as No_of_ekl_attempt,
G.first_EKL_Attempt_temp as first_EKL_Attempt_date_time,
G.first_Seller_Attempt_temp as first_Seller_Attempt_date_time,
G.last_EKL_Attempt_temp as last_EKL_Attempt_date_time,
G.last_Seller_Attempt_temp as last_Seller_Attempt_date_time,
G.first_attempt_owner as first_attempt_owner,
G.last_attempt_owner as last_attempt_owner,
G.mp_pickup_compliance_new,
G.mp_pickup_new_promise_date_key,
G.bag_receive_at_mh_datetime,
G.bag_receive_at_mh_date_key,
G.bag_receive_at_mh_time_key,
G.consignment_receive_at_mh_datetime,
G.consignment_receive_at_mh_date_key,
G.consignment_receive_at_mh_time_key,
G.rtd_to_tc_rec_bdays,
G.picked_to_dispatch_bdays,
G.rtd_to_first_ofp_rec_bdays,
G.bag_tracking_id,
G.bag_source_hub_id_key,
G.bag_consignment_id,
G.last_updated_time,
G.shipment_id,
G.mp_last_out_for_pickup_date_key,
G.mp_last_out_for_pickup_time_key,
G.mp_pickup_cancelled_date,
G.mp_pickup_cancelled_date_key,
G.mp_pickup_cancelled_time_key,
G.mp_dispatched_to_ph_date as mp_dispatched_to_ph_date_time,
G.mp_dispatched_to_ph_date_key,
G.mp_dispatched_to_ph_time_key,
G.mp_received_at_seller_date as mp_received_at_seller_date_time,
G.mp_received_at_seller_date_key,
G.mp_received_at_seller_time_key,
if(not ISNULL(G.mp_received_at_seller_date),1,0) as mp_hhd_flag,
zonetype,
G.mp_received_at_ph_actual_date_key,
G.mp_received_at_ph_actual_time_key,
G.dispatchservice,
G.managed_by,
G.bag_lzn_tag,
G.bag_destination_hub_id_key,
G.bag_dispatched_datetime,
G.bag_dispatched_date_key,
G.bag_dispatched_time_key,
G.bag_created_at_datetime,
G.bag_created_at_date_key,
G.bag_created_at_time_key,
G.bag_timestamp,
G.bag_date_key,
G.bag_time_key,
G.bag_by_handheld_timestamp,
G.bag_by_handheld_date_key,
G.bag_by_handheld_time_key,
G.bag_event

from
(Select 
D.tracking_id,
D.pickuprequest_id,
D.zonetype,
D.mp_pickup_hub_id,
D.mp_pickup_hub_key,
D.mp_requested_date_key,
D.mp_requested_date,
D.mp_day,
D.reqested_hour,
D.mp_pickup_promise_date,
D.mp_pickup_compliance,
D.mp_first_out_for_pickup_date,
D.mp_first_out_for_pickup_date_key,
D.mp_first_out_for_pickup_time_key,
D.mp_received_at_origin_date_key,
D.mp_received_at_origin_date,
D.mp_dispatched_to_tc_date_key,
D.mp_dispatched_to_tc_date,
D.mp_received_at_tc_date_key,
D.mp_received_at_tc_date,
D.mp_num_of_pk_attempts,
D.mp_num_of_pk_reattempts,
D.current_hub_type,
D.current_hub_id_key,
D.mp_current_status,
D.mp_requested_time_key,
D.mp_received_at_origin_time_key,
D.mp_dispatched_to_tc_time_key,
D.mp_received_at_tc_time_key,
D.mp_last_out_for_pickup_date,
D.seller_id_key,
D.rtd_to_picked_days,
D.rtd_to_tc_rec_days,
D.picked_to_dispatch_days,
D.dispatched_to_rec_at_tc_days,
D.rtd_to_tc_rec_bdays,
D.picked_to_dispatch_bdays,
D.rtd_to_first_ofp_rec_bdays,
F.No_Seller_reattempt,
F.No_of_ekl_attempt,
F.first_EKL_Attempt_temp,
F.first_Seller_Attempt_temp,
F.last_EKL_Attempt_temp,
F.last_Seller_Attempt_temp,
if(F.first_EKL_Attempt_temp IS NULL,if(F.first_Seller_Attempt_temp IS NULL,NULL,'Seller'),if(F.first_Seller_Attempt_temp IS NULL,'EKL',if(F.first_EKL_Attempt_temp<F.first_Seller_Attempt_temp,'EKL','Seller'))) as first_attempt_owner,
if(F.last_EKL_Attempt_temp IS NULL,if(F.last_Seller_Attempt_temp IS NULL,NULL,'Seller'),if(F.last_Seller_Attempt_temp IS NULL,'EKL',if(F.last_EKL_Attempt_temp>F.last_Seller_Attempt_temp,'EKL','Seller'))) as last_attempt_owner,
if(FROM_UNIXTIME( UNIX_TIMESTAMP() ,'u')=1,lookup_date(D.mp_pickup_promise_date),
if(datediff(to_date(FROM_UNIXTIME(UNIX_TIMESTAMP())),to_date(D.mp_pickup_promise_date))>=2 AND UPPER(D.mp_current_status) NOT IN ('CANCELLED') 
AND (D.mp_received_at_origin_date IS NULL OR datediff(to_date(FROM_UNIXTIME( UNIX_TIMESTAMP())),to_date(D.mp_received_at_origin_date))=1) ,
lookup_date(date_sub(FROM_UNIXTIME(UNIX_TIMESTAMP()),1)),
if(D.mp_requested_date_key=D.mp_received_at_origin_date_key, D.mp_requested_date_key,lookup_date(D.mp_pickup_promise_date)))) as mp_pickup_new_promise_date_key,
if(D.mp_last_out_for_pickup_date<=D.mp_pickup_promise_date,1,0) as mp_pickup_compliance_new,
D.bag_receive_at_mh_datetime,
D.bag_receive_at_mh_date_key,
D.bag_receive_at_mh_time_key,
D.consignment_receive_at_mh_datetime,
D.consignment_receive_at_mh_date_key,
D.consignment_receive_at_mh_time_key,
D.bag_consignment_id,
D.bag_tracking_id,
D.shipment_id,
D.bag_source_hub_id_key,
D.bag_lzn_tag,
D.bag_destination_hub_id_key,
D.bag_dispatched_datetime,
D.bag_dispatched_date_key,
D.bag_dispatched_time_key,
D.bag_created_at_datetime,
D.bag_created_at_date_key,
D.bag_created_at_time_key,
D.bag_timestamp,
D.bag_date_key,
D.bag_time_key,
D.bag_by_handheld_timestamp,
D.bag_by_handheld_date_key,
D.bag_by_handheld_time_key,
D.bag_event,
D.last_updated_time,
D.mp_last_out_for_pickup_date_key,
D.mp_last_out_for_pickup_time_key,
D.mp_pickup_cancelled_date,
D.mp_pickup_cancelled_date_key,
D.mp_pickup_cancelled_time_key,
D.mp_dispatched_to_ph_date,
D.mp_dispatched_to_ph_date_key,
D.mp_dispatched_to_ph_time_key,
D.mp_received_at_seller_date,
D.mp_received_at_seller_date_key,
D.mp_received_at_seller_time_key,
D.mp_received_at_ph_actual_date_key,
D.mp_received_at_ph_actual_time_key,
D.dispatchservice,
if(D.mp_pickup_hub_id in (801 ,1049 ,803 ,1004 ,406 ,615 ,400 ,809 ,999 ,799 ,508 ,899 ,1061 ,1523 ,361 ,326 ,328 ,325 ,1521 ,1512 ,327 ,354 ,724 ,426 ,1724 ,353 ,1985 ,1725 ,1993 ,1992 ,2116 ,1046 ,1038 ,820 ,795 ,1012 ,454 ,379 ,334 ,374 ,380 ,338 ,330 ,336 ,331 ,340 ,337 ,332 ,798 ,1036 ,718 ,1037 ,1008 ,596 ,802 ,377 ,606 ,1048 ,821 ,362 ,365 ,363 ,364 ,1064 ,1068 ,1039 ,1009 ,1893 ,1991 ,1030 ,452 ,1017 ,1047 ,1035 ,789 ,816 ,1065 ,401 ,369 ,826 ,610 ,705 ,885 ,1001 ,1005 ,819 ,1006 ,807 ,1044 ,1003 ,1010 ,824 ,823 ,822 ,825 ,367 ,1033 ,1032 ,1771 ,785 ,1041 ,1016 ,1000 ,814 ,1951 ,677 ,733 ,1944 ,372 ,1070 ,1019 ,810 ,573 ,991 ,1029 ,1028 ,1434 ,561 ,1540 ,1945 ,346 ,1007 ,1002 ,1063 ,509 ,1027 ,794 ,796 ,995 ,811 ,812 ,792 ,1069 ,370 ,371 ,378 ,2204 ,2216 ,2226 ,2336 ,2350 ,791 ,2337 ,2338 ,2340 ,2341 ,2342 ,2339 ,345 ,3173,818),'LM','FM') as managed_by


from
(select 
C.tracking_id as tracking_id,
B.pickuprequest_id as pickuprequest_id,
B.zonetype as zonetype,
C.mp_pickup_hub as mp_pickup_hub_id,
lookupkey('facility_id',C.mp_pickup_hub) as mp_pickup_hub_key,
lookup_date(cast(C.mp_requested_date as timestamp)) as mp_requested_date_key,
C.mp_requested_date as mp_requested_date,
if( (C.mp_requested_date IS NOT NULL) , from_unixtime(unix_timestamp(C.mp_requested_date,'yyyyMMdd'),'u') , NULL) as mp_day,
hour(C.mp_requested_date) as reqested_hour,
if(C.dispatchservice='REGULAR',(

if(C.mp_requested_date IS NOT NULL,
if((from_unixtime(unix_timestamp(C.mp_requested_date,'yyyyMMdd'),'u')=6 and hour(C.mp_requested_date)>9),
date_add(to_date(C.mp_requested_date),2),
if((from_unixtime(unix_timestamp(C.mp_requested_date,'yyyyMMdd'),'u')=7 and hour(C.mp_requested_date)<10),
date_add(to_date(C.mp_requested_date),1),
if(hour(C.mp_requested_date)>9,date_add(to_date(C.mp_requested_date),1),to_date(C.mp_requested_date)))),NULL)),

(if(C.mp_requested_date IS NOT NULL,
if((from_unixtime(unix_timestamp(C.mp_requested_date,'yyyyMMdd'),'u')=6 and hour(C.mp_requested_date)>13),
date_add(to_date(C.mp_requested_date),2),
if((from_unixtime(unix_timestamp(C.mp_requested_date,'yyyyMMdd'),'u')=7 and hour(C.mp_requested_date)<14),
date_add(to_date(C.mp_requested_date),1),
if(hour(C.mp_requested_date)>13,date_add(to_date(C.mp_requested_date),1),to_date(C.mp_requested_date)))),NULL))) as mp_pickup_promise_date,

if(datediff(to_date(C.mp_requested_date),to_date(C.mp_first_out_for_pickup_date))=0 and hour(C.mp_requested_date)<10,1, 
if(datediff(to_date(C.mp_requested_date),to_date(C.mp_first_out_for_pickup_date))<=1 and hour(C.mp_requested_date)>9,1,0)) as mp_pickup_compliance,
C.mp_first_out_for_pickup_date as mp_first_out_for_pickup_date,
lookup_date(cast(C.mp_first_out_for_pickup_date as timestamp)) as mp_first_out_for_pickup_date_key,
lookup_time(cast(C.mp_first_out_for_pickup_date as timestamp)) as mp_first_out_for_pickup_time_key,
lookup_date(cast(C.mp_received_at_origin_date as timestamp)) as mp_received_at_origin_date_key,
C.mp_received_at_origin_date as mp_received_at_origin_date,
C.mp_dispatched_to_ph_date as mp_dispatched_to_ph_date,
C.mp_received_at_seller_date as mp_received_at_seller_date,
C.mp_received_at_ph_date_actual as mp_received_at_ph_date_actual,
lookup_date(cast(C.mp_received_at_ph_date_actual as timestamp)) as mp_received_at_ph_actual_date_key,
lookup_date(cast(C.mp_dispatched_to_ph_date as timestamp)) as mp_dispatched_to_ph_date_key,
lookup_date(cast(C.mp_received_at_seller_date as timestamp)) as mp_received_at_seller_date_key,
lookup_date(cast(C.mp_dispatched_to_tc_date as timestamp)) as mp_dispatched_to_tc_date_key,
C.mp_dispatched_to_tc_date as mp_dispatched_to_tc_date,
lookup_date(cast(C.mp_received_at_tc_date as timestamp)) as mp_received_at_tc_date_key,
C.mp_received_at_tc_date as mp_received_at_tc_date,
C.mp_num_of_pk_attempts_temp as mp_num_of_pk_attempts,
C.mp_num_of_pk_reattempts_temp as mp_num_of_pk_reattempts,
B.current_hub_type as current_hub_type,
B.current_hub_id_key_temp as current_hub_id_key,
B.mp_current_status_temp as mp_current_status,
lookup_time(cast(C.mp_requested_date as timestamp)) as mp_requested_time_key,
lookup_time(cast(C.mp_received_at_origin_date as timestamp)) as mp_received_at_origin_time_key,
lookup_time(cast(C.mp_received_at_ph_date_actual as timestamp)) as mp_received_at_ph_actual_time_key,
lookup_time(cast(C.mp_dispatched_to_ph_date as timestamp))as mp_dispatched_to_ph_time_key,
lookup_time(cast(C.mp_received_at_seller_date as timestamp))as mp_received_at_seller_time_key,
lookup_time(cast(C.mp_dispatched_to_tc_date as timestamp))as mp_dispatched_to_tc_time_key,
lookup_time(cast(C.mp_received_at_tc_date as timestamp)) as mp_received_at_tc_time_key,
C.mp_last_out_for_pickup_date as mp_last_out_for_pickup_date,
lookup_date(cast(C.mp_last_out_for_pickup_date as timestamp)) as mp_last_out_for_pickup_date_key,
lookup_time(cast(C.mp_last_out_for_pickup_date as timestamp)) as mp_last_out_for_pickup_time_key,
B.seller_id_temp as seller_id_key,
if(ISNULL(c.mp_dispatched_to_tc_date),0,1) as mp_dispatch_to_tc_flag,
if(ISNULL(c.mp_received_at_tc_date),0,1) as mp_received_at_tc_flag,
if (ISNULL(c.mp_first_out_for_pickup_date),0,1) as mp_first_out_for_pickup_flag,
if(B.mp_current_status_temp in ('received_at_ph','dispatched_to_mh','received_at_mh'),DATEDIFF(to_date(C.mp_last_out_for_pickup_date),to_date(C.mp_requested_date)),0) as rtd_to_picked_days,
if(B.mp_current_status_temp in ('dispatched_to_mh','received_at_mh'),DATEDIFF(to_date(C.mp_dispatched_to_tc_date),to_date(C.mp_last_out_for_pickup_date)),0)as picked_to_dispatch_days,
if(B.mp_current_status_temp='received_at_mh',DATEDIFF(to_date(C.mp_received_at_tc_date),to_date(C.mp_dispatched_to_tc_date)),0) as dispatched_to_rec_at_tc_days,
if(B.mp_current_status_temp='received_at_mh',DATEDIFF(to_date(C.mp_received_at_tc_date),to_date(C.mp_requested_date)),0) as rtd_to_tc_rec_days,
if(B.mp_current_status_temp='received_at_mh',business_date_diff(SUBSTR(mp_received_at_tc_date,1,19), SUBSTR(mp_requested_date,1,19)),0) as rtd_to_tc_rec_bdays,
if(B.mp_current_status_temp='received_at_mh',business_date_diff(C.mp_received_at_tc_date,C.mp_dispatched_to_tc_date),0) as dispatched_to_rec_at_tc_bdays,
if(mp_current_status_temp in ('dispatched_to_mh','received_at_mh'),business_date_diff(SUBSTR(mp_dispatched_to_tc_date,1,19), SUBSTR(mp_received_at_origin_date,1,19)),0) as picked_to_dispatch_bdays,
if(mp_current_status_temp in ('dispatched_to_mh','received_at_mh'),business_date_diff(SUBSTR(mp_first_out_for_pickup_date,1,19), SUBSTR(mp_requested_date,1,19)),0) as rtd_to_first_ofp_rec_bdays,
B.bag_receive_at_mh_datetime as bag_receive_at_mh_datetime,
lookup_time(cast(B.bag_receive_at_mh_datetime as timestamp)) as bag_receive_at_mh_time_key,
lookup_date(cast(B.bag_receive_at_mh_datetime as timestamp)) as bag_receive_at_mh_date_key,
B.bag_consignment_id,
B.consignment_receive_at_mh_datetime as consignment_receive_at_mh_datetime,
lookup_date(cast(B.consignment_receive_at_mh_datetime as timestamp)) as consignment_receive_at_mh_date_key,
lookup_time(cast(B.consignment_receive_at_mh_datetime as timestamp)) as consignment_receive_at_mh_time_key,
B.bag_tracking_id,
B.shipment_id,
B.bag_lzn_tag,
B.bag_destination_hub_id_key,
B.bag_dispatched_datetime,
lookup_date(cast(B.bag_dispatched_datetime as timestamp)) as bag_dispatched_date_key,
lookup_time(cast(B.bag_dispatched_datetime as timestamp)) as bag_dispatched_time_key,
B.bag_created_at_datetime,
lookup_date(cast(B.bag_created_at_datetime as timestamp)) as bag_created_at_date_key,
lookup_time(cast(B.bag_created_at_datetime as timestamp)) as bag_created_at_time_key,
B.bag_timestamp,
B.bag_date_key,
B.bag_time_key,
B.bag_by_handheld_timestamp,
B.bag_by_handheld_date_key,
B.bag_by_handheld_time_key,
B.bag_event,
B.bag_source_hub_id_key,
C.last_updated_time,
C.mp_pickup_cancelled_date,
lookup_time(cast(C.mp_pickup_cancelled_date as timestamp)) as mp_pickup_cancelled_time_key,
lookup_date(cast(C.mp_pickup_cancelled_date as timestamp)) as mp_pickup_cancelled_date_key,
C.dispatchservice
from
(select
A.tracking_id as tracking_id,
A.dispatchservice as dispatchservice,
min(A.mp_requested_date_temp) as mp_requested_date,
max(A.mp_pickup_hub_temp) as mp_pickup_hub,
min(A.mp_out_for_pickup_date_temp) as mp_first_out_for_pickup_date,
max(A.mp_out_for_pickup_date_temp) as mp_last_out_for_pickup_date,
max(A.mp_received_at_origin_date_temp) as mp_received_at_origin_date,
min(A.mp_received_at_ph_date_actual_temp) as mp_received_at_ph_date_actual,
min(A.mp_dispatched_to_ph_date_temp) as mp_dispatched_to_ph_date,
min(A.mp_received_at_seller_date_temp) as mp_received_at_seller_date,
min(A.mp_dispatched_to_tc_date_temp) as mp_dispatched_to_tc_date,
min(A.mp_received_at_tc_date_temp) as mp_received_at_tc_date,
sum(if(A.mp_status='out_for_pickup',1,0)) as mp_num_of_pk_attempts_temp,
sum(if(A.mp_status='pickup_reattempt',1,0)) as mp_num_of_pk_reattempts_temp,
max(A.updateAt) as last_updated_time,
min(A.mp_pickup_cancelled_date) as mp_pickup_cancelled_date
 
from
(Select `data`.trackingid as tracking_id,

`data`.status as mp_status,
`data`.dispatchservice as dispatchservice,
if(`data`.status='created',`data`.updatedat,NULL) as mp_requested_date_temp,
if(`data`.status='out_for_pickup' or `data`.fulfillmentfacility.owner='pickup_hub',`data`.fulfillmentfacility.ownerid,0) as mp_pickup_hub_temp,
if(`data`.status='out_for_pickup',`data`.updatedat,NULL) as mp_out_for_pickup_date_temp,
if(`data`.status='received_at_ph' or `data`.status='received_at_seller',`data`.updatedat,NULL) as mp_received_at_origin_date_temp,
if(`data`.status='received_at_ph',`data`.updatedat,NULL) as mp_received_at_ph_date_actual_temp,
if(`data`.status='dispatched_to_ph',`data`.updatedat,NULL) as mp_dispatched_to_ph_date_temp,
if(`data`.status='received_at_seller',`data`.updatedat,NULL) as mp_received_at_seller_date_temp,
if(`data`.status='dispatched_to_mh',`data`.updatedat,NULL) as mp_dispatched_to_tc_date_temp,
if(`data`.status='received_at_mh',`data`.updatedat,NULL) as mp_received_at_tc_date_temp ,
if(`data`.status='cancelled',`data`.updatedat,NULL) as mp_pickup_cancelled_date,
`data`.updatedat as updateAt
from bigfoot_journal.dart_wsr_scp_ekl_firstmilepickuprequest_2)A group by A.tracking_id,A.dispatchservice)C 
inner join
(select 
`data`.trackingid as tracking_id,
`data`.pickuprequestid as pickuprequest_id,
`data`.zonetype as zonetype,
`data`.fulfillmentfacility.owner as current_hub_type,
lookupkey('facility_id',`data`.fulfillmentfacility.ownerid) as current_hub_id_key_temp,
lookupkey('seller_hive_dim_key',`data`.source.ownerid) as seller_id_temp,
`data`.status as mp_current_status_temp,
bagshipment.bag_receive_at_mh_datetime as bag_receive_at_mh_datetime,
bagshipment.bag_consignment_id,
bagshipment.consignment_receive_at_mh_datetime,
bagshipment.bag_tracking_id,
bagshipment.shipment_id,
bagshipment.bag_source_hub_id_key,
bagshipment.bag_lzn_tag,
bagshipment.bag_destination_hub_id_key,
bagshipment.bag_dispatched_datetime,
bagshipment.bag_created_at_datetime,
bagshipment.bag_timestamp,
bagshipment.bag_date_key,
bagshipment.bag_time_key,
bagshipment.bag_by_handheld_timestamp,
bagshipment.bag_by_handheld_date_key,
bagshipment.bag_by_handheld_time_key,
bagshipment.bag_event

from bigfoot_snapshot.dart_wsr_scp_ekl_firstmilepickuprequest_2_view pr
left outer join bigfoot_external_neo.scp_ekl__first_mile_shipment_bag_hive_fact bagshipment
on pr.`data`.trackingid=bagshipment.tracking_id
)B
on B.tracking_id=C.tracking_id)D
inner join
(Select
E.tracking_id,
sum(case when E.EKL_Seller_Flag='NON EKL' then 1 else 0 end) as No_Seller_reattempt,
sum(case when E.EKL_Seller_Flag='EKL' then 1 else 0 end) as No_of_ekl_attempt,
min(case when E.EKL_Seller_Flag='EKL' then E.updateAt else null end) as first_EKL_Attempt_temp,
min(case when E.EKL_Seller_Flag='NON EKL' then E.updateAt else null end) as first_Seller_Attempt_temp,
max(case when E.EKL_Seller_Flag='EKL'then E.updateAt else null end) as last_EKL_Attempt_temp,
max(case when E.EKL_Seller_Flag='NON EKL'then E.updateAt else null end) as last_Seller_Attempt_temp
from
(select 
`data`.trackingid as tracking_id,
(case when NOT ISNULL(`data`.remarks) then UPPER(SPLIT(`data`.remarks,":")[0])  else 0 end) as EKL_Seller_Flag,
`data`.updatedat as updateAt
from bigfoot_journal.dart_wsr_scp_ekl_firstmilepickuprequest_2)E group by E.tracking_id)F
on F.tracking_id=D.tracking_id)G;
