INSERT OVERWRITE TABLE geotag_hive_fact
select  tag_id,
address_full,
address_hash,
addr1,
addr2,
city,
country,
pincode_key,
state,
type,
altitude,
source,
date_key,
geo_date_key,
geo_time_key,
device_id,
latitude,
longitude, 
delivery_verification_code_type,
accuracy_level,
is_same_spot_delivery,
agent_id_key,
tasklist_id,
tasklist_type,
received_at_date_key,
received_at_time_key,
location_last_attempt_date_key,
location_last_attempt_time_key,appversion from (select  tag_id,
address_full,
address_hash,
addr1,
addr2,
city,
country,
pincode_key,
state,
type,
altitude,
source,
date_key,
geo_date_key,
geo_time_key,
device_id,
latitude,
longitude, 
delivery_verification_code_type,
accuracy_level,
is_same_spot_delivery,
agent_id_key,
tasklist_id,
tasklist_type,
received_at_date_key,
received_at_time_key,
location_last_attempt_date_key,
location_last_attempt_time_key,
appversion,
row_number() over(partition by tasklist_id,tag_id order by time desc) as rnk
from 
(Select distinct geo.tag_id,
geo.address_full,
geo.address_hash,
geo.addr1,
geo.addr2,
geo.city,
geo.country,
lookupkey('pincode',geo.pincode) as pincode_key,
geo.state,
geo.type,
geo.altitude,
geo.source,
lookup_date(geo.date0) as date_key,
geo.time,
lookup_date(geo.time) as geo_date_key,
lookup_time(geo.time) as geo_time_key,
geo.device_id,
geo.latitude,
geo.longitude, 
geo.delivery_verification_code_type[0] as delivery_verification_code_type,
geo.accuracy_level[0] as accuracy_level,
geo.is_same_spot_delivery[0] as is_same_spot_delivery,
lookupkey('agent_id',geo.agent_id[0]) as agent_id_key,
Case when geo.runsheet_id[0] is not null then concat('Runsheet-',geo.runsheet_id[0]) else concat('Pickupsheet-',geo.pickupsheet_id[0]) end as tasklist_id,
geo.tasklist_type[0] as tasklist_type,
lookup_date(geo.received_at[0]) as received_at_date_key,
lookup_time(geo.received_at[0]) as received_at_time_key,
lookup_date(geo.location_last_attempt_time[0]) as location_last_attempt_date_key,
lookup_time(geo.location_last_attempt_time[0]) as location_last_attempt_time_key,
geo.appversion[0] as appversion
from (SELECT
explode_0.tag_id,
explode_0.address_full,
explode_0.address_hash,
explode_0.addr1,
explode_0.addr2,
explode_0.city,
explode_0.country,
explode_0.pincode,
explode_0.state,
explode_0.type,
explode_0.altitude,
explode_0.source,
explode_0.date0,
explode_0.time,
explode_0.device_id,
explode_0.latitude,
explode_0.longitude, 
collect_set(explode_0.delivery_verification_code_type) as delivery_verification_code_type,
collect_set(explode_0.accuracy_level) as accuracy_level,
collect_set(explode_0.is_same_spot_delivery) as is_same_spot_delivery,
collect_set(explode_0.agent_id) as agent_id,
collect_set(explode_0.runsheet_id) as runsheet_id,
collect_set(explode_0.pickupsheet_id) as pickupsheet_id,
collect_set(explode_0.tasklist_type) as tasklist_type,
collect_set(explode_0.received_at) as received_at,
collect_set(explode_0.location_last_attempt_time) as location_last_attempt_time,
collect_set(explode_0.appversion) as appversion
from (select geo.`data`.tag_id as tag_id,
geo.`data`.address_full,
geo.`data`.address_hash,
geo.`data`.address.addr1 as addr1,
geo.`data`.address.addr2 as addr2,
geo.`data`.address.city as city,
geo.`data`.address.country as country,
geo.`data`.address.pincode as pincode,
geo.`data`.address.state as state,
geo.`data`.altitude,
geo.`data`.source,
geo.`data`.time,
geo.data.`date` as date0,
geo.`data`.tracking_id as device_id,
geo.`data`.latitude as latitude,
geo.`data`.longitude as longitude,
geo.`data`.type,
if(explode_0.key='delivery_verification_code_type',explode_0.value,NULL) as delivery_verification_code_type,
if(explode_0.key='accuracy_level',explode_0.value,NULL) as accuracy_level,
if(explode_0.key='is_same_spot_delivery',explode_0.value,NULL) as is_same_spot_delivery,
if(explode_0.key='agent_id',explode_0.value,NULL) as agent_id,
if(explode_0.key='runsheet_id',explode_0.value,NULL) as runsheet_id,
if(explode_0.key='pickupsheet_id',explode_0.value,NULL) as pickupsheet_id,
Case when explode_0.key='runsheet_id' then 'runsheet' when explode_0.key='pickupsheet_id' then 'pickupsheet' end as tasklist_type,
if(explode_0.key='location_last_attempt_time',explode_0.value,NULL) as location_last_attempt_time,
if(explode_0.key='received_at',explode_0.value,NULL) as received_at,
if(explode_0.key='appVersion',explode_0.value,NULL) as appversion
from bigfoot_journal.dart_wsr_scp_ekl_geotag_5 geo LATERAL VIEW explode(`data`.attributes) exploded_table AS EXPLODE_0
) explode_0 
group by explode_0.tag_id,
explode_0.address_full,
explode_0.address_hash,
explode_0.addr1,
explode_0.addr2,
explode_0.city,
explode_0.country,
explode_0.pincode,
explode_0.state,
explode_0.type,
explode_0.altitude,
explode_0.source,
explode_0.date0,
explode_0.time,
explode_0.device_id,
explode_0.latitude, 
explode_0.longitude) geo) a) b where b.rnk=1;
