INSERT OVERWRITE TABLE first_mile_new_promise_hive_fact
Select 
new_promise.tracking_id,
new_promise.pickuprequest_id,
new_promise.mp_pickup_hub_id,
new_promise.mp_pickup_hub_key,
new_promise.mp_requested_date_key,
new_promise.mp_requested_date_time,
new_promise.mp_day,
new_promise.mp_reqested_date_hour,
new_promise.mp_pickup_promise_date,
new_promise.mp_pickup_compliance,
new_promise.mp_first_out_for_pickup_date_time,
new_promise.mp_first_out_for_pickup_date_key,
new_promise.mp_first_out_for_pickup_time_key,
new_promise.mp_received_at_origin_date_key,
new_promise.mp_received_at_origin_date_time,
new_promise.mp_dispatched_to_tc_date_key,
new_promise.mp_dispatched_to_tc_date_time,
new_promise.mp_received_at_tc_date_key,
new_promise.mp_received_at_tc_date_time,
new_promise.mp_num_of_pk_attempts,
new_promise.mp_num_of_pk_reattempts,
new_promise.current_hub_type,
new_promise.current_hub_id_key,
new_promise.mp_current_status,
new_promise.mp_requested_time_key,
new_promise.mp_received_at_origin_time_key,
new_promise.mp_dispatched_to_tc_time_key,
new_promise.mp_received_at_tc_time_key,
new_promise.mp_last_out_for_pickup_date_time,
new_promise.seller_id_key,
new_promise.mp_pickup_promise_date_key,
new_promise.mp_pending_location,
new_promise.reattempt_flag,
new_promise.mp_dispatch_to_tc_flag,
new_promise.mp_received_at_tc_flag,
new_promise.mp_first_out_for_pickup_flag,
new_promise.rtd_to_picked_days,
new_promise.picked_to_dispatch_to_tc_days,
new_promise.dispatched_to_rec_at_tc_days,
new_promise.rtd_to_tc_rec_days,
new_promise.no_seller_reattempt,
new_promise.no_of_ekl_reattempt,
new_promise.first_ekl_attempt_date_time,
new_promise.first_seller_attempt_date_time,
new_promise.last_ekl_attempt_date_time,
new_promise.last_seller_attempt_date_time,
new_promise.first_attempt_owner,
new_promise.last_attempt_owner,
new_promise.mp_pickup_compliance_new,
new_promise.mp_pickup_new_promise_date_key,
new_promise.bag_receive_at_mh_datetime,
new_promise.bag_receive_at_mh_date_key,
new_promise.bag_receive_at_mh_time_key,
new_promise.consignment_receive_at_mh_datetime,
new_promise.consignment_receive_at_mh_date_key,
new_promise.consignment_receive_at_mh_time_key,
new_promise.rtd_to_tc_rec_bdays,
new_promise.picked_to_dispatch_bdays,
new_promise.rtd_to_first_ofp_rec_bdays,
new_promise_key,
datediff(CONCAT(SUBSTR(new_promise.new_promise_key,1,4),'-',SUBSTR(new_promise.new_promise_key,5,2),'-',SUBSTR(new_promise.new_promise_key,7,2)), CONCAT(SUBSTR(new_promise.mp_pickup_promise_date_key,1,4),'-',SUBSTR(new_promise.mp_pickup_promise_date_key,5,2),'-',SUBSTR(new_promise.mp_pickup_promise_date_key,7,2))) as promise_diff,
datediff(CONCAT(SUBSTR(new_promise.new_promise_key,1,4),'-',SUBSTR(new_promise.new_promise_key,5,2),'-',SUBSTR(new_promise.new_promise_key,7,2)), CONCAT(SUBSTR(new_promise.mp_requested_date_key,1,4),'-',SUBSTR(new_promise.mp_requested_date_key,5,2),'-',SUBSTR(new_promise.mp_requested_date_key,7,2))) as rtc_newpromise_day,
if(datediff(CONCAT(SUBSTR(new_promise.new_promise_key,1,4),'-',SUBSTR(new_promise.new_promise_key,5,2),'-',SUBSTR(new_promise.new_promise_key,7,2)), CONCAT(SUBSTR(new_promise.mp_first_out_for_pickup_date_key,1,4),'-',SUBSTR(new_promise.mp_first_out_for_pickup_date_key,5,2),'-',SUBSTR(new_promise.mp_first_out_for_pickup_date_key,7,2)))>0,0,1) as attempt_compliance,
null as first_ofp_receive_bdays,
new_promise.mp_dispatched_to_ph_date_time,
new_promise.mp_dispatched_to_ph_date_key,
new_promise.mp_dispatched_to_ph_time_key,
new_promise.mp_received_at_seller_date_time,
new_promise.mp_received_at_seller_date_key,
new_promise.mp_received_at_seller_time_key,
new_promise.mp_hhd_flag,
new_promise.zonetype,
new_promise.mp_received_at_ph_actual_date_key,
new_promise.mp_received_at_ph_actual_time_key,
if(new_promise.mp_requested_date_key=new_promise.new_promise_key,new_promise.mp_requested_time_key,1000) as mp_pickup_promise_time_key,
ship.shipment_id,
new_promise.fm_dispatch_tier,
new_promise.managed_by,
new_promise.bag_timestamp,
new_promise.bag_date_key,
new_promise.bag_time_key,
new_promise.bag_by_handheld_timestamp,
new_promise.bag_by_handheld_date_key,
new_promise.bag_by_handheld_time_key,
new_promise.bag_event

from
(select 
new_promise_1.tracking_id,
new_promise_1.pickuprequest_id,
new_promise_1.mp_pickup_hub_id,
new_promise_1.mp_pickup_hub_key,
new_promise_1.mp_requested_date_key,
new_promise_1.mp_requested_date_time,
new_promise_1.mp_day,
new_promise_1.mp_reqested_date_hour,
new_promise_1.mp_pickup_promise_date,
new_promise_1.mp_pickup_compliance,
new_promise_1.mp_first_out_for_pickup_date_time,
new_promise_1.mp_first_out_for_pickup_date_key,
new_promise_1.mp_first_out_for_pickup_time_key,
new_promise_1.mp_received_at_origin_date_key,
new_promise_1.mp_received_at_origin_date_time,
new_promise_1.mp_dispatched_to_tc_date_key,
new_promise_1.mp_dispatched_to_tc_date_time,
new_promise_1.mp_received_at_tc_date_key,
new_promise_1.mp_received_at_tc_date_time,
new_promise_1.mp_num_of_pk_attempts,
new_promise_1.mp_num_of_pk_reattempts,
new_promise_1.current_hub_type,
new_promise_1.current_hub_id_key,
new_promise_1.mp_current_status,
new_promise_1.mp_requested_time_key,
new_promise_1.mp_received_at_origin_time_key,
new_promise_1.mp_dispatched_to_tc_time_key,
new_promise_1.mp_received_at_tc_time_key,
new_promise_1.mp_last_out_for_pickup_date_time,
new_promise_1.seller_id_key,
new_promise_1.mp_pickup_promise_date_key,
new_promise_1.mp_pending_location,
new_promise_1.reattempt_flag,
new_promise_1.mp_dispatch_to_tc_flag,
new_promise_1.mp_received_at_tc_flag,
new_promise_1.mp_first_out_for_pickup_flag,
new_promise_1.rtd_to_picked_days,
new_promise_1.picked_to_dispatch_to_tc_days,
new_promise_1.dispatched_to_rec_at_tc_days,
new_promise_1.rtd_to_tc_rec_days,
new_promise_1.no_seller_reattempt,
new_promise_1.no_of_ekl_reattempt,
new_promise_1.first_ekl_attempt_date_time,
new_promise_1.first_seller_attempt_date_time,
new_promise_1.last_ekl_attempt_date_time,
new_promise_1.last_seller_attempt_date_time,
new_promise_1.first_attempt_owner,
new_promise_1.last_attempt_owner,
new_promise_1.mp_pickup_compliance_new,
new_promise_1.mp_dispatched_to_ph_date_time,
new_promise_1.mp_dispatched_to_ph_date_key,
new_promise_1.mp_dispatched_to_ph_time_key,
new_promise_1.mp_received_at_seller_date_time,
new_promise_1.mp_received_at_seller_date_key,
new_promise_1.mp_received_at_seller_time_key,
new_promise_1.mp_hhd_flag,
new_promise_1.zonetype,
new_promise_1.mp_received_at_ph_actual_date_key,
new_promise_1.mp_received_at_ph_actual_time_key,
new_promise_1.mp_pickup_new_promise_date_key,
new_promise_1.bag_receive_at_mh_datetime,
new_promise_1.bag_receive_at_mh_date_key,
new_promise_1.bag_receive_at_mh_time_key,
new_promise_1.consignment_receive_at_mh_datetime,
new_promise_1.consignment_receive_at_mh_date_key,
new_promise_1.consignment_receive_at_mh_time_key,
new_promise_1.rtd_to_tc_rec_bdays,
new_promise_1.picked_to_dispatch_bdays,
new_promise_1.rtd_to_first_ofp_rec_bdays,
new_promise_1.fm_dispatch_tier,
new_promise_1.managed_by,
new_promise_1.bag_timestamp,
new_promise_1.bag_date_key,
new_promise_1.bag_time_key,
new_promise_1.bag_by_handheld_timestamp,
new_promise_1.bag_by_handheld_date_key,
new_promise_1.bag_by_handheld_time_key,
new_promise_1.bag_event,
if(HH.HH_next_working_date_key IS NOT NULL,HH.HH_next_working_date_key,new_promise_1.new_promise_key_1) as new_promise_key

from
(select fmpr.tracking_id,
fmpr.pickuprequest_id,
fmpr.mp_pickup_hub_id,
fmpr.mp_pickup_hub_key,
fmpr.mp_requested_date_key,
fmpr.mp_requested_date_time,
fmpr.mp_day,
fmpr.mp_reqested_date_hour,
fmpr.mp_pickup_promise_date,
fmpr.mp_pickup_compliance,
fmpr.mp_first_out_for_pickup_date_time,
fmpr.mp_first_out_for_pickup_date_key,
fmpr.mp_first_out_for_pickup_time_key,
fmpr.mp_received_at_origin_date_key,
fmpr.mp_received_at_origin_date_time,
fmpr.mp_dispatched_to_tc_date_key,
fmpr.mp_dispatched_to_tc_date_time,
fmpr.mp_received_at_tc_date_key,
fmpr.mp_received_at_tc_date_time,
fmpr.mp_num_of_pk_attempts,
fmpr.mp_num_of_pk_reattempts,
fmpr.current_hub_type,
fmpr.current_hub_id_key,
fmpr.mp_current_status,
fmpr.mp_requested_time_key,
fmpr.mp_received_at_origin_time_key,
fmpr.mp_dispatched_to_tc_time_key,
fmpr.mp_received_at_tc_time_key,
fmpr.mp_last_out_for_pickup_date_time,
fmpr.seller_id_key,
fmpr.mp_pickup_promise_date_key,
fmpr.mp_pending_location,
fmpr.reattempt_flag,
fmpr.mp_dispatch_to_tc_flag,
fmpr.mp_received_at_tc_flag,
fmpr.mp_first_out_for_pickup_flag,
fmpr.rtd_to_picked_days,
fmpr.picked_to_dispatch_to_tc_days,
fmpr.dispatched_to_rec_at_tc_days,
fmpr.rtd_to_tc_rec_days,
fmpr.no_seller_reattempt,
fmpr.no_of_ekl_reattempt,
fmpr.first_ekl_attempt_date_time,
fmpr.first_seller_attempt_date_time,
fmpr.last_ekl_attempt_date_time,
fmpr.last_seller_attempt_date_time,
fmpr.first_attempt_owner,
fmpr.last_attempt_owner,
fmpr.mp_pickup_compliance_new,
fmpr.mp_dispatched_to_ph_date_time,
fmpr.mp_dispatched_to_ph_date_key,
fmpr.mp_dispatched_to_ph_time_key,
fmpr.mp_received_at_seller_date_time,
fmpr.mp_received_at_seller_date_key,
fmpr.mp_received_at_seller_time_key,
fmpr.mp_hhd_flag,
fmpr.zonetype,
fmpr.mp_received_at_ph_actual_date_key,
fmpr.mp_received_at_ph_actual_time_key,
fmpr.mp_pickup_new_promise_date_key,
fmpr.bag_receive_at_mh_datetime,
fmpr.bag_receive_at_mh_date_key,
fmpr.bag_receive_at_mh_time_key,
fmpr.consignment_receive_at_mh_datetime,
fmpr.consignment_receive_at_mh_date_key,
fmpr.consignment_receive_at_mh_time_key,
fmpr.rtd_to_tc_rec_bdays,
fmpr.picked_to_dispatch_bdays,
fmpr.rtd_to_first_ofp_rec_bdays,
if(SH.next_working_date_key IS NOT NULL,SH.next_working_date_key,fmpr.mp_pickup_promise_date_key) as new_promise_key_1,
fmpr.fm_dispatch_tier,
fmpr.managed_by,
fmpr.bag_timestamp,
fmpr.bag_date_key,
fmpr.bag_time_key,
fmpr.bag_by_handheld_timestamp,
fmpr.bag_by_handheld_date_key,
fmpr.bag_by_handheld_time_key,
fmpr.bag_event  

from bigfoot_external_neo.scp_ekl__first_mile_pickup_request_hive_fact  fmpr 
left join 
(select 
A.seller_key as sh_seller_id_key,A.calenderdate_key as holiday_date_key,min(case when C.calenderdate_key is null then lookup_date(date_add(B.calenderdatetime,1)) else null end) as next_working_date_key

from bigfoot_external_neo.scp_ekl__first_mile_seller_holiday_fact A 
left join bigfoot_external_neo.scp_ekl__first_mile_seller_holiday_fact B on (A.seller_key=B.seller_key  )
left join bigfoot_external_neo.scp_ekl__first_mile_seller_holiday_fact C on (B.seller_key=C.seller_key and to_date(C.calenderdatetime)=date_add(B.calenderdatetime,1))
where A.calenderdate_key<=B.calenderdate_key 
group by A.seller_key,A.calenderdate_key) SH
on (fmpr.seller_id_key=SH.sh_seller_id_key and fmpr.mp_pickup_promise_date_key=SH.holiday_date_key)) new_promise_1

left join
(select 
A.`data`.hubId as hh_hub_id,lookup_date(A.`data`.holidayDate) as hh_holiday_date_key,min(case when C.`data`.holidayDate is null then lookup_date(date_add(B.`data`.holidayDate,1)) else null end) as hh_next_working_date_key
from bigfoot_journal.dart_wsr_scp_ekl_firstmilehubholidays_1_0 A 
left join bigfoot_journal.dart_wsr_scp_ekl_firstmilehubholidays_1_0 B on (A.`data`.hubId=B.`data`.hubId  )
left join bigfoot_journal.dart_wsr_scp_ekl_firstmilehubholidays_1_0 C on (B.`data`.hubId=C.`data`.hubId and to_date(C.`data`.holidayDate)=date_add(B.`data`.holidayDate,1))
where A.`data`.holidayDate<=B.`data`.holidayDate and A.`data`.isholidayflag=TRUE
group by A.`data`.hubId,lookup_date(A.`data`.holidayDate)) HH
on (HH.hh_hub_id=new_promise_1.mp_pickup_hub_id and HH.hh_holiday_date_key=new_promise_1.new_promise_key_1) )new_promise


left join
(select 
vendor_tracking_id,
shipment_id 
from bigfoot_external_neo.scp_ekl__shipment_l0_90_fact 
where vendor_tracking_id is not null and vendor_tracking_id NOT IN ('not_assigned')) ship
on ship.vendor_tracking_id=new_promise.tracking_id ;
