INSERT OVERWRITE TABLE first_mile_breach_90_testv2_fact

select  tracking_id,
if( mp_dispatched_to_tc_date_key is not null and (mp_dispatched_to_tc_date_key< new_promise_key  or (mp_dispatched_to_tc_date_key= new_promise_key  and mp_dispatched_to_tc_time_key<=2159) ) , 'Not_breached',
if( isnull(mp_first_out_for_pickup_date_key) or datediff(CONCAT(SUBSTR(mp_first_out_for_pickup_date_key,1,4),'-',SUBSTR(mp_first_out_for_pickup_date_key,5,2),'-',SUBSTR(mp_first_out_for_pickup_date_key,7,2)),CONCAT(SUBSTR(new_promise_key,1,4),'-',SUBSTR(new_promise_key,5,2),'-',SUBSTR(new_promise_key,7,2)))>=1 ,'Attempt_breach',   
if((no_of_ekl_reattempt>=no_seller_reattempt) and (no_of_ekl_reattempt<>0 or no_seller_reattempt<>0) and (mp_received_at_origin_date_key is null  or mp_received_at_origin_date_key<>new_promise_key) ,'EKL_issue',
if(no_seller_reattempt>no_of_ekl_reattempt and (no_of_ekl_reattempt<>0 or no_seller_reattempt<>0) and (mp_received_at_origin_date_key is null or mp_received_at_origin_date_key<>new_promise_key) ,'Seller_Related_issue',
if(mp_received_at_origin_date_key> new_promise_key  or (mp_received_at_origin_date_key= new_promise_key  and mp_received_at_origin_time_key>2159),'Pickup_breach',
if(((mp_received_at_origin_date_key= new_promise_key or mp_received_at_origin_date_key<new_promise_key)   and (((isnull(mp_dispatched_to_tc_date_key) and not IsNull(mp_received_at_origin_date_key) and mp_current_status NOT in ('pickup_reattempt','cancelled')) or (mp_dispatched_to_tc_date_key>mp_received_at_origin_date_key) or (mp_dispatched_to_tc_date_key=mp_received_at_origin_date_key and mp_dispatched_to_tc_time_key>2159)))) ,'PH_breach_not_dispatch_same_day',
if((isnull(mp_dispatched_to_tc_date_key) and not IsNull(mp_received_at_origin_date_key) and mp_current_status in  ('pickup_reattempt','cancelled')),'Return_to_Seller'
,'RCA'))))))) as Breach_Bucket,

if(mp_dispatched_to_tc_date_key is not null and (mp_dispatched_to_tc_date_key< new_promise_key  or (mp_dispatched_to_tc_date_key= new_promise_key  and mp_dispatched_to_tc_time_key<=2159) ) and (bag_receive_at_mh_date_key <= new_promise_key or mp_received_at_tc_date_key<= new_promise_key),0,1)  AS breach_flag,
new_promise_key as mp_pickup_promise_date_key, 
mp_pickup_hub_key,
seller_id_key,
mp_current_status,
mp_requested_date_key,
mp_requested_time_key,
mp_first_out_for_pickup_date_key,
mp_first_out_for_pickup_time_key,
mp_last_out_for_pickup_date_time,
mp_dispatched_to_tc_date_key,
mp_dispatched_to_tc_time_key,
mp_received_at_tc_date_key,
mp_received_at_tc_time_key,
mp_num_of_pk_attempts,
mp_num_of_pk_reattempts,
no_seller_reattempt,
no_of_ekl_reattempt,
mp_received_at_origin_date_key,
mp_received_at_origin_time_key,
if( mp_dispatched_to_tc_date_key is not null and (mp_dispatched_to_tc_date_key< new_promise_key  or (mp_dispatched_to_tc_date_key= new_promise_key  and mp_dispatched_to_tc_time_key<=2159) ) , 'Not_breached',
if( isnull(mp_first_out_for_pickup_date_key) or datediff(CONCAT(SUBSTR(mp_first_out_for_pickup_date_key,1,4),'-',SUBSTR(mp_first_out_for_pickup_date_key,5,2),'-',SUBSTR(mp_first_out_for_pickup_date_key,7,2)),CONCAT(SUBSTR(new_promise_key,1,4),'-',SUBSTR(new_promise_key,5,2),'-',SUBSTR(new_promise_key,7,2)))>=1 ,'First_Mile_Attempt_breach',   
if((no_of_ekl_reattempt>=no_seller_reattempt) and (no_of_ekl_reattempt<>0 or no_seller_reattempt<>0) and (mp_received_at_origin_date_key is null  or mp_received_at_origin_date_key<>new_promise_key) ,'First_Mile_EKL_issue',
if(no_seller_reattempt>no_of_ekl_reattempt and (no_of_ekl_reattempt<>0 or no_seller_reattempt<>0) and (mp_received_at_origin_date_key is null or mp_received_at_origin_date_key<>new_promise_key) ,'02 First_Mile_Seller_Reattempt_Breach',
if(mp_received_at_origin_date_key> new_promise_key  or (mp_received_at_origin_date_key= new_promise_key  and mp_received_at_origin_time_key>2159),'First_Mile_Pickup_breach',
if(((mp_received_at_origin_date_key= new_promise_key or mp_received_at_origin_date_key< new_promise_key) and (((isnull(mp_dispatched_to_tc_date_key) and not IsNull(mp_received_at_origin_date_key) and mp_current_status NOT in ('pickup_reattempt','cancelled')) or (mp_dispatched_to_tc_date_key>mp_received_at_origin_date_key) or (mp_dispatched_to_tc_date_key=mp_received_at_origin_date_key and mp_dispatched_to_tc_time_key>2159)))) ,'First_Mile_PH_breach_not_dispatch_same_day',
if((isnull(mp_dispatched_to_tc_date_key) and not IsNull(mp_received_at_origin_date_key) and mp_current_status in ('pickup_reattempt','cancelled')),'First_Mile_Return_to_Seller',
'First_Mile_RCA'))))))) as LP_CP_Breach_Bucket,
bag_receive_at_mh_datetime,
bag_receive_at_mh_date_key,
bag_receive_at_mh_time_key,
consignment_receive_at_mh_datetime,
consignment_receive_at_mh_date_key,
consignment_receive_at_mh_time_key,
mp_dispatched_to_ph_date_time,
mp_dispatched_to_ph_date_key,
mp_dispatched_to_ph_time_key,
mp_received_at_seller_date_time,
mp_received_at_seller_date_key,
mp_received_at_seller_time_key,
mp_hhd_flag,
zonetype,
fm_dispatch_tier,
if(consignment_receive_at_mh_date_key is not null and (consignment_receive_at_mh_date_key< new_promise_key  or (consignment_receive_at_mh_date_key= new_promise_key ) ) , 'Not_breached',
if( isnull(mp_first_out_for_pickup_date_key) or datediff(CONCAT(SUBSTR(mp_first_out_for_pickup_date_key,1,4),'-',SUBSTR(mp_first_out_for_pickup_date_key,5,2),'-',SUBSTR(mp_first_out_for_pickup_date_key,7,2)),CONCAT(SUBSTR(new_promise_key,1,4),'-',SUBSTR(new_promise_key,5,2),'-',SUBSTR(new_promise_key,7,2)))>=1 ,'Attempt_breach',   
if((no_of_ekl_reattempt>=no_seller_reattempt) and (no_of_ekl_reattempt<>0 or no_seller_reattempt<>0) and (mp_received_at_origin_date_key is null  or mp_received_at_origin_date_key<>new_promise_key) ,'EKL_issue',
if(no_seller_reattempt>no_of_ekl_reattempt and (no_of_ekl_reattempt<>0 or no_seller_reattempt<>0) and (mp_received_at_origin_date_key is null or mp_received_at_origin_date_key<>new_promise_key) ,'Seller_Related_issue',
if(mp_received_at_origin_date_key> new_promise_key  or (mp_received_at_origin_date_key=new_promise_key  and mp_received_at_origin_time_key>2159),'Pickup_breach',
if(((mp_received_at_origin_date_key= new_promise_key or mp_received_at_origin_date_key<new_promise_key)  and (((isnull(mp_dispatched_to_tc_date_key) and not IsNull(mp_received_at_origin_date_key)) or (mp_dispatched_to_tc_date_key>mp_received_at_origin_date_key) or (mp_dispatched_to_tc_date_key=mp_received_at_origin_date_key and mp_dispatched_to_tc_time_key>2159)))) ,'PH_breach_not_dispatch_same_day',
if(((mp_dispatched_to_tc_date_key= new_promise_key  or mp_dispatched_to_tc_date_key<new_promise_key) and (((isnull(consignment_receive_at_mh_date_key) and not IsNull(mp_dispatched_to_tc_date_key)) or (consignment_receive_at_mh_date_key>mp_dispatched_to_tc_date_key)))) ,'PH_Consignment_not_received_same_day',
'RCA'))))))) as Express_Breach_Bucket
from 
bigfoot_external_neo.scp_ekl__first_mile_new_promise_hive_fact;

