INSERT OVERWRITE TABLE shipment_first_last_consignment_map_l1_90_fact
SELECT FC_LC.vendor_tracking_id,
FC_LC.first_consignment AS shipment_first_consignment_id,
FC_LC.last_consignment AS shipment_last_consignment_id,
lookup_date(FirstCons.consignment_create_datetime) AS shipment_first_consignment_create_date_key,
lookup_time(FirstCons.consignment_create_datetime) AS shipment_first_consignment_create_time_key,
lookup_date(LastCons.consignment_create_datetime) AS shipment_last_consignment_create_date_key,
lookup_time(LastCons.consignment_create_datetime) AS shipment_last_consignment_create_time_key,
LastCons.consignment_status AS shipment_last_consignment_status,
lookup_date(LastCons.consignment_eta_datetime) AS shipment_last_consignment_eta_date_key,
lookup_time(LastCons.consignment_eta_datetime) AS shipment_last_consignment_eta_time_key,
lookup_date(LastCons.consignment_received_datetime) AS shipment_last_consignment_receive_date_key,
lookup_time(LastCons.consignment_received_datetime) AS shipment_last_consignment_receive_time_key,
LastCons.consignment_destination_hub_id AS shipment_last_consignment_hub_id,
LastCons.consignment_type AS shipment_last_consignment_type,
LastCons.consignment_status_date_time AS shipment_last_consignment_updated_time,
LastCons.consignment_received_datetime AS shipment_last_consignment_receive_time,
LastCons.consignment_eta_datetime AS shipment_last_consignment_expected_time,
LastCons.consignment_destination_hub_id AS shipment_last_consignment_destination_hub_id,
FirstCons.consignment_destination_hub_id AS shipment_first_consignment_destination_hub_id,
LastCons.consignment_mode AS shipment_last_consignment_mode,
LastCons.consignment_awb_number AS shipment_last_consignment_awb_number,
LastCons.consignment_movement_flag AS shipment_last_consignment_movement_flag,
LastCons.consignment_co_loader AS shipment_last_consignment_co_loader,
lookup_date(FirstCons.consignment_received_datetime) AS shipment_first_consignment_receive_date_key,
lookup_time(FirstCons.consignment_received_datetime) AS shipment_first_consignment_receive_time_key,
FirstCons.consignment_type AS shipment_first_consignment_type,
FirstCons.consignment_mode AS shipment_first_consignment_mode,
FirstCons.consignment_awb_number AS shipment_first_consignment_awb_number,
FirstCons.consignment_movement_flag AS shipment_first_consignment_movement_flag,
FirstCons.consignment_co_loader AS shipment_first_consignment_co_loader,
LastCons.consignment_breach_flag AS shipment_last_consignment_breach_flag,
LastCons.consignment_destination_hub_type AS shipment_last_consignment_destination_hub_type,
LastCons.consignment_source_hub_type AS shipment_last_consignment_source_hub_type,
LastCons.consignment_source_hub_id AS shipment_last_consignment_source_hub_id,
lookup_date(LastCons.consignment_eta_datetime) AS shipment_last_consignment_expected_date_key,
lookup_time(LastCons.consignment_eta_datetime) AS shipment_last_consignment_expected_time_key,
LastCons.consignment_eta_datetime AS shipment_last_consignment_expected_datetime,
FirstCons.consignment_connection_id AS shipment_first_consignment_connection_id,
LastCons.consignment_connection_id AS shipment_last_consignment_connection_id
FROM
(SELECT Ship.vendor_tracking_id,
min(cast(split(ConsMap1.consignment_id, "-")[1] AS INT)) AS first_consignment, 
max(cast(split(ConsMap2.consignment_id, "-")[1] AS INT)) AS last_consignment
FROM
(SELECT shipment_id AS vendor_tracking_id, min(first_time) AS first_cons_time, max(first_time) AS last_cons_time
FROM bigfoot_external_neo.scp_ekl__shipment_consignment_map_l1_90_fact
GROUP BY shipment_id) Ship
INNER JOIN bigfoot_external_neo.scp_ekl__shipment_consignment_map_l1_90_fact ConsMap1 ON Ship.vendor_tracking_id = ConsMap1.shipment_id
AND ConsMap1.first_time = Ship.first_cons_time
INNER JOIN bigfoot_external_neo.scp_ekl__shipment_consignment_map_l1_90_fact ConsMap2 ON Ship.vendor_tracking_id = ConsMap2.shipment_id
AND ConsMap2.first_time = Ship.last_cons_time
group by Ship.vendor_tracking_id
) FC_LC
LEFT JOIN bigfoot_external_neo.scp_ekl__consignment_l1_90_fact FirstCons ON FirstCons.consignment_id = FC_LC.first_consignment
LEFT JOIN bigfoot_external_neo.scp_ekl__consignment_l1_90_fact LastCons ON LastCons.consignment_id = FC_LC.last_consignment;
