INSERT overwrite TABLE fc_profiler_volumetric_estimate_final_hive_fact 
SELECT vendor_tracking_id, 
       shipment_id, 
       shipment_dead_weight, 
       profiled_flag, 
       seller_type, 
       no_of_items, 
       shipping_category, 
       ekl_shipment_type, 
       profiled_hub_id, 
       profiled_hub_type, 
       shipment_created_at_datetime, 
       packing_box_used_name, 
       suggested_packing_box_name, 
       volumetric_weight, 
       volumetric_weight_source, 
       etl_datetime, 
       warehouse_vol_source, 
       median_fsn_vol_wt, 
       sum_warehouse_vol_wt, 
       max_warehouse_vol_wt, 
       profiled_volume_in_gms, 
       non_fa_volumetric_estimate, 
       non_fa_volumetric_estimate_source, 
       seller_dead_weight, 
       seller_volumetric_weight, 
       profiled_dead_weight_at_source, 
       profiled_volumetric_weight_at_source	,
       product_detail_fsn	   
FROM   ( 
              SELECT fvef.vendor_tracking_id, 
                     fvef.shipment_id, 
                     fvef.shipment_dead_weight, 
                     fvef.profiled_flag, 
                     fvef.seller_type, 
                     fvef.no_of_items, 
                     fvef.shipping_category, 
                     fvef.ekl_shipment_type, 
                     fvef.profiled_hub_id, 
                     fvef.profiled_hub_type, 
                     fvef.shipment_created_at_datetime, 
                     fvef.packing_box_used_name, 
                     fvef.suggested_packing_box_name, 
                     fvef.volumetric_weight, 
                     fvef.volumetric_weight_source, 
                     CURRENT_TIMESTAMP AS etl_datetime, 
                     fvef.warehouse_vol_source, 
                     fvef.median_fsn_vol_wt, 
                     fvef.sum_warehouse_vol_wt, 
                     fvef.max_warehouse_vol_wt, 
                     NULL                                                           AS profiled_volume_in_gms,
                     fvef.volumetric_weight                                         AS non_fa_volumetric_estimate,
                     NULL                                                           AS non_fa_volumetric_estimate_source,
                     fvef.shipment_dead_weight                                      AS seller_dead_weight,
                     fvef.volumetric_weight                                         AS seller_volumetric_weight,
                     fvef.shipment_dead_weight                                      AS profiled_dead_weight_at_source,
                     fvef.volumetric_weight                                         AS profiled_volumetric_weight_at_source,
					 fvef.product_detail_fsn
              FROM   bigfoot_external_neo.scp_ekl__fa_volumetric_estimate_hive_fact AS fvef 
              UNION ALL 
              SELECT nfvef.vendor_tracking_id, 
                     nfvef.shipment_id, 
                     nfvef.shipment_dead_weight, 
                     nfvef.profiled_flag, 
                     nfvef.seller_type, 
                     nfvef.no_of_items, 
                     nfvef.shipping_category, 
                     nfvef.ekl_shipment_type, 
                     nfvef.profiled_hub_id, 
                     nfvef.profiled_hub_type, 
                     nfvef.shipment_created_at_datetime, 
                     nfvef.packing_box_used_name, 
                     nfvef.suggested_packing_box_name, 
                     nfvef.volumetric_weight, 
                     nfvef.volumetric_weight_source, 
                     CURRENT_TIMESTAMP AS etl_datetime, 
                     NULL              AS warehouse_vol_source, 
                     nfvef.median_fsn_vol_wt AS median_fsn_vol_wt, 
                     NULL              AS sum_warehouse_vol_wt, 
                     NULL              AS max_warehouse_vol_wt, 
                     nfvef.profiled_volume_in_gms, 
                     nfvef.non_fa_volumetric_estimate, 
                     nfvef.non_fa_volumetric_estimate_source, 
                     nfvef.seller_dead_weight, 
                     nfvef.seller_volumetric_weight, 
                     nfvef.profiled_dead_weight_at_source, 
                     nfvef.profiled_volumetric_weight_at_source,
                     nfvef.product_detail_fsn					 
              FROM   bigfoot_external_neo.scp_ekl__non_fa_volumetric_estimate_hive_fact AS nfvef) union_query;
